dotnet/llilc

- Documentation/index.md
- Documentation/llilc-arch.md
- Documentation/llilc-jit-eh.md
- Documentation/llilc-reader.md
* Fix broken fragment identifiers.
* Use relative links when possible.
* Remove unused {#mainpage} from index.md
* Use consistent formatting for subheaders; e.g.
Use:
Instead of:
Subheader
----------
> Improve documentation, as described below.

- include/Jit/utility.h
- lib/Jit/options.cpp
- lib/Jit/utility.cpp
On *Nix platforms, a `wchar_t` is actually a UTF-32 codepoint; on Windows,
it is a UTF-16 codepoint. Thus, when the CLR headers say `wchar_t`, what
they actually mean is `char16_t`. Fix the JIT options code to deal in
UTF-16 strings on all platforms.
> Fix some wide string issues in JIT options.

- lib/Jit/LLILCJit.cpp
The global dumpLevel routine was left in the code by a mistaken merge.  This change just removes the dead code.
> Remove global dumpLevel routine.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
We were using the same calculation at all callsites, so just remove the
parameter and do the calculation in the method itself; this simplifies
adding new callsites.
Also remove the ReaderBase parameter, since it's always the same as the
instance pointer.
> Move initial capacity calculation into createStack

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
This allows creating point blocks for points other than CurrInstrOffset.
> Allow explicit offset argument to createPointBlock

- lib/Reader/readerir.cpp
Check for the case that the current block is a point block for point
CurrInstrOffset; in that case, using NextInstrOffset for the split would
extend the block's range, so preserve the smaller end offset.
> Allow splitting point blocks in splitCurrentBlock

- lib/Reader/readerir.cpp
If we're splitting a block that we've already marked as not propagating
stack (i.e. a point block), preserve that annotation on the newly-created
tail block (since it represents the same flow point as exit from the
original block).  The bit is left set on the original block (which becomes
the head); it's up to the caller to know why it's splitting the block here
and whether stack is propagated at this split point.
> Preserve stack-propagating-ness in fgSplitBlock

- lib/Reader/reader.cpp
Without this, we were leaving its start and end offsets both set to zero,
which makes it appear not to contain its children and confuses things.
> Annotate root region as covering entire method

- include/Reader/reader.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Update `maintainOperandStacks` and new block processing in `msilToIR` to
accomodate this.  Some EH-related blocks will have only exception dispatch
point blocks as predecessors.
> Allow blocks to have zero stack-propagating preds

- lib/Jit/LLILCJit.cpp
We don't want the LLVM dynamic loader to try and resolve external symbols by name. As things stand today, if jitted code contains external symbol references we have a bug in the jit.
This anticipates a change I'm about to make in LLVM where I enable the ability to resolve externals by name for x64 COFF RtDyld, since other LLVM clients need this.
Once both changes are in we'll get a somewhat clearer error message when Jitted code has an unsat, e.g.
`LLVM ERROR: Program used external function '__chkstk' which could not be resolved!`
> Disable symbol searching.

- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
Fix a check in GenIR::simpleFieldAddress that was allowing bad field indices for StructGEP.
Add NYIs for struct type mismatches.
Treat verification errors as compilation failures.
> Fix and workarounds for Roslyn.

- include/Jit/LLILCJit.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
CoreCLR's COMPLUS_GCCONSERVATIVE flag tells the runtime to use
conservative when set. LLILC also used this flag to determine whether
the insertion and lowering of statepoint intrinsics are done.
With this change, steatpoints are inserted if the COMPLUS_INSERTSTATEPOINTS
switch is set, regardless of the COMPLUS_GCCONSERVATIVE flag.
This allows testing of LLILC Jit with statepoints inserted. That is, to
check that the code itself is still correct, regardless of the GC information.
Issue #32
> Separate options for ConservativeGC and Inserting Safepoints

- include/Jit/utility.h
- lib/Jit/utility.cpp
When including the header file for other purpose, this caused ambiguous name conflicts for other types.
By convention, I moved it to cpp file where it is used.
> Fix for using namespace llvm inside header file

- include/Pal/LLILCPal.h
- include/Reader/reader.h
- include/clr/ntimage.h
- Remove unused __cdecl attributes where necessary
- Change a zero-sized array to a one-sized array; 0-sized arrays are not
standard C++
- Give names to two anonymous structs in ntimage.h
> Fix a number of warnings from clang.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Add calls to MONITOR_ENTER on entry to the method and MONITOR_EXIT on returns.
We can't catch exceptions yet; when we can we will need to add a try/fault for the entire method
so that we can call MONITOR_EXIT on unhandled exceptions.
We have a synchronized method in HelloWorld (System.IO.TextWriter+SyncTextWriter.WriteLine).
I verified that the generated IR looks correct. I also tested with a simple two-thread race that the
behavior of synchronized instance and static methods is as expected.
> Support for synchronized methods.

- include/Reader/readerir.h
- lib/Jit/CMakeLists.txt
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
Getting the LLVM IR right here is not too hard. Note we're zeroing things via the helper since
using LLVM's memset might lead to calls into the CRT.
Most of the challenge here is in getting this IR properly lowered to machine code. I have some
corequisite changes to LLVM for this.
> Implement support for localloc.

- include/Reader/abisignature.h
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
This wraps LLVMBuilder->CreateCall, and will be where the logic goes that
instead creates an invoke with an appropriate exception edge if we're in a
protected region.
I decided to go ahead and split this out from my EH changes and PR it to master since it touches many lines and I expect this aspect of the changes (having a makeCall helper with this signature) to stick.
> Add makeCall wrapper

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Since we allow structs in SSA, the code is similar to that for loading
primitive types.
Change getPrimitiveAddress to getTypedAddress so that it can be used for
both primitive and non-primitive types.
Closes #189.
> Implement loadNonPrimitiveObj.

- test/LLILCEnv.ps1
- test/exclusion
25 JIT CSE test cases were added in CoreCLR repo in https://github.com/dotnet/coreclr/pull/738.
12 of them have issues if run with LLILC. Exclude them
in both powershell and python scripts. Issue https://github.com/dotnet/llilc/issues/462
is created for investigation of the causes.
> Exclude JIT CSE test cases that has issue with LLILC

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
We hit these cases in IL stubs in Roslyn bring-up.
Closes #468.
> Handle merging of nativeint and unmanaged pointers as PHI operand types.

- lib/Reader/readerir.cpp
We had an off-by-1 error in the allocation of the argument array.
Because of that we had an extra null argument in the helper call which
resulted in llvm verification failure when building Roslyn.
Closes #469.
> Fix MD array creation.

- lib/Reader/readerir.cpp
It's possible that while adding the fields to a struct we may complete the struct
due to circular type definitions. Detect that case and return the result right away.
Closes #467.
> Fix llvm assert when calling StructType::setBody from getClassType.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Point blocks created in the first pass might not yet have a spot for their
point available to insert them into the block list.  This change:
1. adds tracking of whether the first pass is completed or not,
2. initializes the NodeOffsetListArray earlier so it will be available
when point blocks are craeted in readerPrePass,
2. during the first pass (and pre-pass), updates point block creation to call
fgAddNodeMSILOffset to ensure that an appropriate spot will be created
for it in fgReplaceBranchTargets, and
3. in replaceFlowGraphNodeUses (which gets called from
fgReplaceBranchTargets), moves the point node to the appropriate spot.
This gets first-pass created point blocks in correct MSIL offset order
before we process them in the second pass.
Also update endfinally block creation to use …
> Reposition first-pass point blocks

- test/LLILCEnv.ps1
- test/exclusion
39 inlining optimization test cases were added in CoreCLR repo in dotnet/coreclr#776.
3 of them have issue if run with LLILC, Inline_Handler, Inline_Vars, InlineThrow.
Exclude them in both powershell and python scripts. Issue dotnet#487
is created for investigation of the causes.
> Exclude Inline optimization test cases that have issue with LLILC

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Map each `BasicBlock` to its containing `EHRegion`.
Generate code for catch handlers, and landing pads with appropriate exception dispatch for catch-protected try regions.
Generate `invoke` with appropriate unwind label rather than `call` for calls that may throw.
Other handler types are still discarded; the plan is to push catch regions through the full phase list before moving on to other handler types (to get an earlier handle on unknowns).
When a function is compiled that contains a catch handler, it goes through reading, verification, and dumping (if enabled), but then is discarded (since otherwise the downstream processing would crash on the first method with a catch handler).
This PR is for a merge into the EH branch; doing a PR now to get the work-in-progress reviewed, but keeping …
> Implement reader support for catch handlers and may-throw calls

- include/Reader/abisignature.h
- include/Reader/readerir.h
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
Unmanaged calls require some extra machinery to setup the necessary data
structures and inform the runtime that control is entering unmanaged code.
This code is comprised of two pieces:
- Unmanaged call frame setup, which occurs in the method prolog, and
- GC mode transition, which occurs at an unmanaged call site.
Unmanaged call frame setup is relatively simple and can be accomplished
entirely in LLVM IR.
The GC transition, however, is more complicated due to the constraints
that must be satisfied for the GC to operate correctly when unmanaged code
is running. In particular, managed code must not run if the GC has been
informed that unmanaged code is running. The approach taken by other
managed code generators (e.g. RyuJIT) in order to meet this constraint is
to inform the GC of the …
> Support indirect unmanaged calls.

- CODE_OWNERS.TXT
List of code areas and their owners.  Owners are responsible for ensuring that code is reviewed and are the final word on changes in that area.
@AndyAyersMS, @pgavlin, @swaroop-sridhar, @erozenfeld, @JosephTremoulet 
Initial list of code owners to make it easier to find the right person to talk to.
> Add list of code owners

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
All uses of addressOfLeaf can instead be replaced with uses of
addressOfValue.
With these changes, LLILC is able to compile all methods
necessary for the Hello World sample at https://github.com/dotnet/corefxlab/tree/master/demos/CoreClrConsoleApplications/HelloWorld.
> Remove addressOfLeaf.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
If CORINFO_OPT_INIT_LOCALS is set, zero initialize all locals;
otherwise, zero initialize gc pointers and structs with gc pointers.
This bug was causing bad codegen and runtime failures in 4
methods in baby Roslyn.
Closes #495.
> Zero initialize locals.

- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
This is the case where we don't need writer barrier which was already filtered out.
I use cpBlk which falls back to memcpy helper call to implement this.
I've verified this with a unit test which will commit to our test asset in separate.
> Support for storing value type to static field

- test/exclusion.targets
12 Generics\Exceptions test cases were added to CoreCLR in https://github.com/dotnet/coreclr/pull/839.
12 of them have failures with LLILC. Exclude them. Issue https://github.com/dotnet/llilc/issues/513 is created for investigation.
This PR is supposed to be retested after CoreCLR PR https://github.com/dotnet/coreclr/pull/839 is merged.
> Exclude Generics\Exceptions test cases that have failures with LLILC

- include/Jit/EEMemoryManager.h
- lib/Jit/EEMemoryManager.cpp
This is a no-op for now, but is required for correctness given that we
also overload registerEHFrames.
> Override deregisterEHFrames.

- test/exclusion.targets
Exclude Methodical\MDArray tests since llilc fails on them when ngen is disabled.
> Exclude Methodical\MDArray tests. 

- test/LLILCTestEnv.cmd
- test/llilc_runtest.py
This is needed because recent builds of the core CLR provide an ngen image for mscorlib.
Closes #490.
> Update test environment to make sure we're jitting everything.

- lib/Reader/readerir.cpp
Zero-extend the result of ICmp and FCmp from i1 to i32 instead of sign-extending it.
Now the result of ICmp and FCmp is 0 or 1 instead of 0 or -1.
This was causing bad codegen for a couple of Roslyn methods.
Closes #517.
> Fix for GenIR::cmp

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Indirect call signatures may not specify the type of the 'this' parameter
of the target method. To handle this case, infer the type of the 'this'
parameter from the type of the 'this' argument. This is consistent with
the behavior prescribed by ECMA-335, which states that the type of the
'this' argument should be assumed to be correct in this case (see section
III.3.20).
> Infer the type of 'this' in indirect calls.

- include/Reader/reader.h
- lib/Reader/reader.cpp
The #ifdefs controlling the inclusion of printMSIL were using incorrect
preprocessor symbols. This method can be used from a debugger to dump
the IL for a method being compiled.
> Enable ReaderBase::printMSIL in debug builds.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
This fixes #489 and #529.
The test `fgtest2` mentioned in #489 still fails, but that's because it throws an exception in the test itself.
> Preemptively add predecessor operands for PHI nodes and implement LLVM's dead block removal

- test/exclusion.targets
Now that Microsoft/llvm#35 is in, enable some dependent tests.
> Enable tests that were failing because they needed prolog stack probes.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
This is a simple-minded implementation of `loadAndBox` that loads the value and then passes it off to the box handler.
Closes #300.
For primitives and value types the box handler will immediately turn around and store the value so it can pass the value's address to the box helper, which then loads the value and stores it into the box payload. I've left optimizing this path as a TODO and will open a linked issue.
> Implement loadAndBox

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
`endfinally` and `endfault` are the same MSIL instruction (distinguished by
whether the enclosing region's type is `fault` or `finally`).  Accomodate
both by changing the `getInnermostFinallyRegion` helper to also find
`fault`s (and rename it to `getInnermostFaultOrFinallyRegion`), adding
`fgMakeEndFault` parallel to `fgMakeEndFinally`, and invoking one or the
other according to the discovered region type.  Also get rid of the
superfluous `fgMakeEndFinallyHelper` routine.
`fgMakeEndFault` just generates an UnreachableInst for now (since handlers
are stubbed out).
Closes #393
> Implement EndFault stub support

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
This change inserts casts when the incoming (and in one case) the outgoing types are not as expected.
In our current tests these unexpected types are references to System.__Canon. This can represent arrays and strings as well as other reference types.
Closes #392.
> Support for array and string operations on unexpected types.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
This adds support for xadd* and xchg*.  Closes #531.
> Implement support for some binary interlocked intrinsics.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Other JITs either
a) do not optimize this path, or
b) only optimize here if the incoming argument is the result of lowering
a ldtoken instruction.
We don't yet have the ability do detect (b); stick with (a) in the meantime.
> Stub out getValueFromRuntimeHandle.

- test/exclusion.targets
Add Issue ItemMetaData to ItemGroup ExcludeList in excusion.targets
for each test case so that when a known issue is fixed we know which
tests to re-enable. Some of the issue numbers are relatively general
and more like a placeholder. As investigation goes on and we become
clearer about the causes, more specific issue number will replace the
placeholder.
> Add Issue ItemMetaData to ItemGroup ExcludeList in exclusion.targets 

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Closes #275.
Types with explicit layout may have fields that overlap one another (aka union types). Before this change we'd fail to compile any method that referenced one of these union types. We now model them as best we can using LLVM types.
LLVM doesn't provide a strong way to describe unions. Instead we generally provide a byte array that covers the extent of the union as a representative placeholder. That means for some fields there is no exact LLMV type counterpart. Downstream consumers cope with this as follows: for any field within the extent of a set of overlapping fields, we omit that field handle from the `FieldIndexMap`, so that when a ldfld or similar goes to find out what LLVM type index to use, it comes up empty-handed. We already had a fall-back path here to simply use the …
> Implement support for union types.

- include/Reader/reader.h
- lib/Reader/GenIRStubs.cpp
- lib/Reader/reader.cpp
- irNodeSetRegion : we won't be mapping individual instructions to their
regions, the call to do this for endfinally has already been removed
(4bd6a1e), and the call to set this on `throw` nodes in the first pass
is broken since we don't generate the throwing `call`/`invoke` until
the second pass.
- irNodeBranchSetMSILOffset : we won't be recording offsets on individual
instructions, and the call for `throw` nodes is broken as for
`irNodeSetRegion`
> Remove two vestigial IRNode property setters

- Documentation/llilc-reader.md
- include/Jit/LLILCJit.h
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Implement arrayGet, arraySet, and arrayAddress to expand 2D and 3D
array accesses inline; allow runtime helper to do the expansions
for arrays of other dimensions.
Fix getTypedAddress to deal with ldind.ref with a nativeint arg.
(This was a new test failure after unblocking methods with md array
accesses).
Remove NYI for intrinsics in GenIR::genCall since only a fixed set
of intrinsics is expected to be expanded there; the rest should be
turned into runtime helper calls. Note that ReaderBase::rdrCall also
looks at intrinsics.
Add printMSIL() to dump msil for the current method.
Closes #530.
Closes #540.
Closes #560.
> Implement multidimensional array access intrinsics.

- CMakeLists.txt
- include/CMakeLists.txt
- include/GcInfo/GcInfo.h
- include/GcInfo/GcInfoUtil.h
- include/GcInfo/eexcp.h
- include/Jit/LLILCJit.h
- include/Pal/LLILCPal.h
- include/clr/misc.h
- lib/CMakeLists.txt
- lib/GcInfo/CMakeLists.txt
- lib/GcInfo/GcInfoUtil.cpp
- lib/Jit/CMakeLists.txt
- lib/Jit/LLILCJit.cpp
This change build LLILC with CoreCLR's GcInfoEncoding Library.
-> The GcInfoEncoder headers and implementation are available in CoreCLR's
Output directory.
-> include\GcInfoUtil provides (alternate implementations for) some
data-structures and utilities used by the encoder
-> LLILC generates GcInfo correctly using the encoder.
GcInfoUtil provides the following utilities used by the GcInfoEncoder:
1) Logging functions used by the encoder
2) Helpers for bit-manipulation and overflow checking
3) A simple allocator (using new and delete)
4) SList -- a singly linked list that supports insert-at-tail.
This is a subset of SList in CoreCLR tree, with only necessary functionality.
5) CQuickSort - A simple quick sort implementation with comparer
overridden by the GcInfo encoder library -- from the …
> Use GcInfo Encoding in LLILC

- lib/Jit/LLILCJit.cpp
Re-apply the change that was accidentally removed in 93b82adac634fe93c7b798f6d2a855b601ee9310. Verification errors
result in assert or compilation failure.
Closes #335.
> Verification errors should result in compilation failure

- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
Patchable statepoint support added 2 additional arguments to the start of
the statepoint intrinsic. Pass zeroes for these arguments, as we don't need
either of them.
> Adjust GC transition codegen to accomodate patchable statepoints.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
`binaryOpType` now follows Ecma-355 table III.2 with some exceptions for internal use and for patterns seen in IL stubs.
No diffs in the existing test cases.
Closes #558.
> Update binaryOpType to handle more cases.

- include/Reader/abi.h
- include/Reader/readerir.h
- lib/Reader/abi.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
RyuJIT expects all calls to/from managed code to follow a producer-extends
model for integral arguments that are less than four bytes in size.
> Enable zero and sign extension for call args/results.

- lib/Reader/readerir.cpp
GenIR::arraySet was not converting the value to be stored from its stack
type to its actual type. This change adds the missing call to
convertFromStackType.
> Fix a bug in GenIR::arraySet.

- test/llilc_checkpass.py
llilc_checkpass was previously checking for failures by hunting for lines
in a diff that began with '-'. Unfortunately, this is not accurate: most
importantly, it fails to account for the fact that methods may simply no
longer be submitted for compilation (generally due to changes to the
libraries or tests).
This change switches to a set-based implementation in order to accurately
detect methods meeting any of the following criteria:
- Compiled cleanly in the baseline and are now failing to compile
- Failed to compile in the baseline and are now compiling cleanly
- Processed in the baseline but not processed now
- Not processed in the baseline and processed now
A run is only a failure if there are methods that used to compile cleanly
that now fail to compile. A count for each category is …
> Improve llilc_checkpass failure detection.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
They were causing struct type mismatches due to generic sharing
and also had potential optimization issues.
No values of StructType are allowed on the operand stack.
Instead pointers to structs are pushed to the stack and
recorded in StructPointers set.
When a struct needs to be loaded we make a copy of the struct
and return a pointer to the copy.
addressOfValue doesn't need to copy the struct. Instead a pointer
to the struct is copied.
Struct type mismatches on the stack and at PHI joins
are handled by casting the pointers representing the structs.
Closes #407.
Closes #441.
> Disallow first-class aggregates in LLVM IR we are generating.

- lib/Reader/readerir.cpp
This is a more aggressive workaround for #557. We already have the ability to tolerate missing fields in codegen. So we fall back to that if we're building up a model of a ref class and can't account for all of its fields.
For value classes we still insist that we get a complete picture, because we intend to use the LLVM types to produce GC info.
> Handle ref classes with missing fields.

- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
This implements basic support for the `mkrefany` opcode. I created a simple test but System.TypedReference is not exposed by contract assemblies so getting the test to build as part of core CLR tests is nontrivial. Note `refanyval` was buggy before the change to not allow structs on the stack. Now it works ok but is somewhat fragile.
Closes #298.
> Implement support for mkrefany.

- test/exclusion.targets
This covers the tests under JIT/Methodical. All but one of the exclusions are
due to issues involving EH or GC. The outlier is tracked by issue #592.
> Add exclusions for new JIT tests.

- lib/Reader/readerir.cpp
This was causing [unexpected type in load/store primitive] in two CoreCLR tests:
static_passing_class01 and static_passing_struct01. The result of getStaticFieldAddress
is used as a pointer for a constrained virtual call. Dereferencing this pointer for
CORINFO_TYPE_REFANY resulted in the error.
With this fix we are at 100% when compiling currently enabled CoreCLR tests.
Closes #588.
> Return a properly typed pointer from getStaticFieldAddress.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
The intrinsic returns the length of the specified dimension
for a vector or a multidimensional array.
Closes #561.
> Implement Array_GetDimLength intrinsic.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
refanyval was returning an interior pointer to a byte instead of
an interior pointer to the type given as an operand to the
refanyval instruction. This was causing downstream code to assert.
> Fix the type of refanyval.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
- test/exclusion.targets
- test/llilc_checkpass.py
This cleans up an additional six NYIs in the new tests; the remaining
four are still under investigation. This also fixes llilc_checkpass for
compatibility with Python 3.x, as well as correcting an inverted
condition in success/failure diff measurement.
> Implement refAnyType and fix llilc_checkpass.

- test/exclusion.targets
All remaining test cases were added under JIT\Generics in CoreCLR repo in dotnet/coreclr#1045.
8 of them have issues if run with LLILC. Exclude them. Issue #596 is created for
investigation of the causes.
> Exclude JIT\Generics tests that have issues with LLILC

- include/Jit/utility.h
- lib/Jit/jitoptions.cpp
- lib/Jit/utility.cpp
This string specifies which methods should be fed to the Alternate JIT.
The patterns recognized are as follows:
/// *         - all methods.
/// M         - method M, with any number of arguments.
/// C:M       - method M in class C.
///
/// C can be a simple class name, or a namespace.classname.  For example,
/// "Sort" or "System.Array:Sort".
///
/// M can be followed by the pattern (number) to specify its number of
/// arguments.  For example, .ctor(0) or Adjust(2)
///
//  Eg: "  foo  Ns.MyClass:bar System.Array.Sort " holds 3 patterns.
#
#	modified:   include/Jit/utility.h
#	modified:   lib/Jit/jitoptions.cpp
#	modified:   lib/Jit/utility.cpp
#
> Parse the string value of COMPLUS_AltJit.  This specifies which methods

- test/exclusion.targets
CoreCLR PR dotnet/coreclr#1059 added Regression\VS_is64_JIT tests. Some of the tests cannot run with LLILC. Exclude them. Issue https://github.com/dotnet/llilc/issues/601 is created for investigation.
> Exclude Regression\VS-ia64-JIT tests that have issues with LLILC

- include/Pal/earlyincludes.h
- lib/Jit/LLILCJit.cpp
- lib/Jit/jitoptions.cpp
- lib/Reader/GenIRStubs.cpp
- lib/Reader/abi.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
LLVM now include a coff.h file that defines in enumeration types
constants with the same names that Windows defines using
in the scope of the windows #defines. To avoid that we
include related include files early before anyone has includes
windows.h.
Two other small changes made:
1. The TargetOptions.NoFramePointerElim field no longer exists.
For now I just commented out references to it, but we need to
decide if there is something else we need to do to
ensure we get a frame pointer.
2. The parameters of the LLVMBUILDER->CreateCall method changed.
Now need to pass args. We only used this for making NOPs, so
pass empty args.
> LLILC changes needed to merge latest LLVM.

- include/clr/misc.h
- lib/Reader/readerir.cpp
ECMA-335 supports addition and subtraction with overflow under the rules
given in table III.8. Because overflowing arithmetic in LLVM requires
calling an intrinsic that only accepts integral arguments, supporting
these operations requires converting the incoming operands to an
intermediate integral type, then converting the result to the ultimate
result type.
This also includes a small fix for errors encountered when compiling with
GCC 4.9.2 on Linux.
> Support {add,sub}.ovf.un when the result is a pointer.

- lib/Jit/LLILCJit.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
LLVM now has a GC-Strategy for supporting CoreCLR runtime.
So use this gc-strategy for functions generated by LLILC.
Expected CQ Impact
No impact on generated code is expected, because CoreCLR gc-strategy
is currently identical to statepoint-example GC.
> Use CoreCLR GCStrategy in LLILC

- lib/Jit/LLILCJit.cpp
Call Core and Scalar opts initializers so that the
dependencies for Safepoint placement and rewriting 
are initialized correctly.
> Initialize Scalar opts

- Documentation/llilc-arch.md
- include/Jit/LLILCJit.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
This will simplify some aspects of funclet management, and also gets LLILC
on top of the newer jitting framework that active development is focused
on.
ORC jits are created by composing `layers`.  LLILC's functionality is
covered by two "off-the-shelf" layers: the IRCompileLayer (using the
SimpleComplier utility) for compiling IR to machine code, and the
ObjectLinkingLayer for resolving fixups and relocations and interfacing
with the EEMemoryManager to load the machine code into appropriate memory.
Closes #610
> Switch to ORC jit infrastructure

- test/exclusion.targets
Core CLR PR dotnet/coreclr#1088 added multiple test directories under Regression. Three of the test cases failed if run with LLILC. https://github.com/dotnet/llilc/issues/616 is created for investigation. Exclude the test case for now.
> Exclude Regression\CLR-x86-EJIT test case that has issue with LLILC

- include/Reader/reader.h
- lib/Reader/readerir.cpp
- Change the ASSERTM macro in the reader to use `assert` rather than
`debugError` in order to avoid losing the message argument
- In GenIR::convertFromStackType, allow zero extension to native uint
- In GenIR::binaryOpType, handle subtraction of one managed pointer
from another managed pointer as per ECMA-335 Table III.2
- In GenIR::mdArrayRefAddr, convert array indicies from stack types to
actual types for consitency with ECMA-335 III.1.6
- In GenIR::arrayGetDimLength, handle cases where the array argument is
an opaque System.Array reference
- In GenIR::cmp, allow comparison between floats and doubles by extending
the former to the size of the latter
> Multiple small bug fixes.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
We had some code to deal with possible cycles in type graphs but it wasn't complete.
This commit has the following changes:
1. The mechanism for deferring and resolving types of aggregate fields is changed.
We now pass around a list that collects all aggregates whose fields weren't resolved.
These aggregates are resolved only after all fields of the top-level aggregate are resolved.
2. When resolving fields, in addition to deferring resolution of class types , we defer resolution
of both class types and struct types when the field is of a pointer to class or struct type.
3. We have the same rules for deferring resolution of array element types as we do for field types.
Examples that these changes fix:
================
class C {
B b;
}
struct A {
C c;
}
struct B {
A a;
}
(Resolution of B …
> Rework circular type resolution.

- include/Jit/EEMemoryManager.h
- include/Jit/LLILCJit.h
- lib/Jit/EEMemoryManager.cpp
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
This is a PR for changes going into the EH branch.  They enable emission and execution of simple catch handlers (nested handlers and references to locals NYI) when built against LLVM with corresponding changes (Microsoft/llvm#43).  The approach to Windows-style EH support in LLVM is [undergoing a change](http://thread.gmane.org/gmane.comp.compilers.llvm.devel/85783) that will necessitate reworking at least the reader portion of these changes.  The EEMemoryManager changes, or something along these lines, will likely survive (but see [this llvmdev thread](http://thread.gmane.org/gmane.comp.compilers.llvm.devel/86316) for discussion of the approach).  I'm parking these changes in the EH branch so anyone curious can see where things are/were heading and provide feedback, and planning shift my …
> Emit catch clauses

- test/exclusion.targets
PR dotnet/coreclr#1118 add JIT\Regression\CLR-x86-JIT\V1-M09 test cases for JIT.
One of them is failing with LLILC. JIT\Regression\CLR-x86-JIT\V1-M09\b15864\b15864 due to EH issue.
Exclude it.
> Exclude CLR-x86-JIT\V1-M09 test case that has issue with LLILC

- include/Jit/LLILCJit.h
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Jit/CMakeLists.txt
- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
This change adds support to LLILC to send source line information to
LLVM and then on to the CLR EE to be used in debugging. This change
adds:
* Support to the Reader to capture IL offsets and set them as debug
locations for instructions. To do so, this change adds calls to the
DIBuilder to create debug information for functions, and then to set
the DebugLoc information for each instruction. The debugger expects
offsets for the following: the start of a function, when the stack is
empty, and when we have a call instruction. To get this all piped
through LLVM properly, we had to insert extra nops for instances where
the stack is empty, but we were looking at a store for a local (this
gets swallowed by the following instruction). We also required extra
nops around branches to get …
> Add Debug Line Information Support to LLILC

- include/Jit/LLILCJit.h
- lib/Jit/LLILCJit.cpp
The jit layers are really an implementation detail, and don't need to be
exposed from LLILCJit.h.  Even in LLILCJit.cpp, they're only used to
declare the layers; this change inlines them into the declarations (using
decltype(PreviousLayer) to avoid excessive repetition of lower layer
types) and removes them entirely.
This avoids needing to make parallel changes in the typedefs and
declarations when adding/changing layers.
> Remove typedefs for jit layers

- CMakeLists.txt
In Microsoft/llvm@84b1665, LLVM stopped supplying a custom argument parser in favor of using the CMake builtin. We need to do likewise in LLIIC.
This is a prerequisite to merging latest LLVM sources.
> Fix Cmake for upcoming LLVM merge

- test/exclusion.targets
This will be necessary once https://github.com/dotnet/coreclr/pull/1169 is merged.
> Exclude failures from refactored IL tests.

- include/Jit/LLILCJit.h
- lib/Jit/CMakeLists.txt
- lib/Jit/EEMemoryManager.cpp
- lib/Jit/LLILCJit.cpp
LLILC doesn't need its own NullResolver class now that LLVM provides one as a utility.
Also remove some vestigial MCJit references.
> Use orc::NullResolver

- lib/Jit/LLILCJit.cpp
- test/exclusion.targets
- clang was complaining about the unqualified reference to `OptLevel` on
line 226
- The code model passed during target machine selection was incorrect
for JITted code, which caused bad relocations on Linux. This may also
be the cause of #639.
> Fix two small bugs in LLILCJit.

- lib/Jit/LLILCJit.cpp
LLVM renamed SymbolRef::getSize to SymbolRef::getCommonSize,
so change LLILC code to use the new name.
> Change getSize to getCommonSize to match LLVM change.

- include/Jit/LLILCJit.h
- lib/Jit/LLILCJit.cpp
This layer just needs to call the memory manager's reserveUnwindSpace
method on each object as it passes through; use the
orc::ObjectTransformLayer utility rather than a custom object layer.
> Use ObjectTransformLayer to reserve unwind space

- lib/Jit/LLILCJit.cpp
LLVM changed the signature of SymbolRef::getType() by removing
its parameter, so modify call to match.
> Change call to SymbolRef::getType() to match LLVM changed signature.

- Documentation/Areas-To-Contribute.md
- Documentation/Background.md
- Documentation/Code-Formatting.md
- Documentation/Contributing.md
- Documentation/Developer-Workflow.md
- Documentation/Getting-Started-For-Linux-and-OS-X.md
- Documentation/Getting-Started-For-Windows.md
- Documentation/Long-Running-Branch-Workflow.md
- Documentation/Setup-With-LLILC-Out-Of-LLVM-Tree.md
- Documentation/Testing.md
- Documentation/Welcome.md
- Documentation/llilc-Coding-Conventions-and-Commenting-Style.md
- Documentation/llilc-faq.md
- Documentation/llilc-milestones.md
- README.md
Bulk move with minimal editing (just wrapping lines and fixing up links)
to get our documentation in a place where changes can be made via pull
request and it will be versioned with the code.
Resolves #612.
Resolves #622.
> Move wiki contents to Documentation directory

- Documentation/llilc-gc-transition.md
- Documentation/llilc-gc.md
This updates the GC document to conform with LLVM terminology for GC
transitions and adds a document describing how such transitions are
supported for CoreCLR in LLILC and LLVM.
> Document the GC transition design.

- include/Jit/EEMemoryManager.h
- include/Reader/abi.h
- include/Reader/abisignature.h
- lib/GcInfo/CMakeLists.txt
- lib/Jit/CMakeLists.txt
- lib/Jit/LLILCJit.cpp
- lib/Reader/CMakeLists.txt
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Our cmake files were inadvertently clobbering build flags set by LLVM's cmake files when trying to append -EHsc.  Fix that, and the ensuing fall-out from enabling -W4.
> Fix build flags and several compiler warnings

- include/Jit/LLILCJit.h
- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
Because we do not yet properly do type substitution on the
result of calls to generic-shared methods (#676), sometimes
the result of a call is not the correct type. In particular
sometimes we attempt an array operation on such a result
when the type of the result is not an array type. Typically
it is something like the "canonical" type used to represent
any reference type.
In such cases we need to cast the value to an LLVM type that
represents the correct MSIL type. Prior to this fix we were
just using a single "array of reference" type for these,
but that gives incorrect address arithmetic when the element
type has a size different from the size of a reference.
This change restructures and extends a number of methods
so that array types referencing the proper element type
are created. …
> Ensure Array operations use correct Array type.

- lib/Jit/LLILCJit.cpp
The SymbolRef::getName and SymbolRef.getAddress methods
now use ErrorOr<T> return types to return either an
error code or the desired value. The calls to these
were changed to capture the ErrorOr<T> value and
then test for error. If no error then extract the
value and proceed to use it.
> Modify SymbolRef getName and getAddress calls for new signature.

- include/Jit/compiler.h
- lib/Jit/LLILCJit.cpp
New functor will be extended to implement LLILC specific phase lists.
> Make copy of ORC SimpleCompiler functor for LLILCCompiler

- lib/Reader/readerir.cpp
LLVM renamed Intrinsic::frameescape to be Intrinsic::localescape,
so use the new name.
> Modify to use Intrinsic::localescape instead of Intrinsic::frameescape.

- lib/Jit/LLILCJit.cpp
This will be necessary when we outline filter functions.
> Verify and dump entire module, not just function.

- test/llilc_runtest.py
To run tests with llilc ngen'd mscorlib, we need to not disable zap.
This change adds a switch to llilc_runtest, --ngen. When passed, we do
not set COMPLUS_ZapDisable.
> Add ngen option to llilc_runtest

- Documentation/llilc-milestones.md
Mark Hello World, and Roslyn Hello World as complete for Windows and Linux. Also add new milestones for Roslyn selfhosted.
> Update milestones to reflect new status.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Filters are outlined during initial IR generation (which includes
explicitly escaping any locals referenced in filters), to simplify
modeling their effects in the IR (invoking the outlined function must be
included as a possible side-effect of any invoke that may throw an
exception, since this must bottom out in a call to the throw helper [which
is external code] and the filter function has external linkage).
The ReaderBase class is unaware of the outlining.  GenIR generates the
filter code inline in the main function (except for an initial point
block) during its main passes, and then moves filter blocks to the correct
function in the readerPostVisit pass that this change adds between reading
MSIL and removing unreachable code.
The CurrentRegion tracked by the reader is used by GenIR to …
> Add support for EH filters

- lib/Jit/EEMemoryManager.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
Use GlobalVariables instead of constants for computing thread trap addresses.
Fix read-only section alignment issue. It was causing an assert in allocateDataSection.
Closes #698.
> Enable ngen for il stubs.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Removing unused blocks may invalidate LLVMBuilder's insert point.
Currently we insert IR to keep generic context alive and IR for security object in readerPostPass,
which runs after removal of unused blocks. That results in AV on some tests with debug llilc jit.
The reason we haven't seen this in the lab is that we use ReleaseWithDebugInfo build.
It uses msvcr120.dll (debug build uses msvcr120d.dll) and its implementation of operator delete
doesn't overwrite deallocated memory. So we are accessing deallocated memory without an AV.
@JosephTremoulet recently introduced readerPostVisit pass in his EH branch.
It runs after reading all MSIL and before removing unused blocks.
So it's a perfect place to move code that inserts IR to keep generic context alive
and IR for security object.
Closes …
> Don't use LLVMBuilder after removing unused blocks.

- include/Jit/utility.h
- include/Reader/abi.h
- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Jit/utility.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- utils/ccformat.py
1) Change ccFormat to run clang-tidy checks by default
Use ccFormat --untidy to only run formatting checks
2) Fix the warnings/errors generated by ccFormat
> ccFormat: Enable Clang-Tidy checks

- include/GcInfo/GcInfo.h
- lib/GcInfo/GcInfo.cpp
Add a missing #ifdef(!NDEBUG) clause around
GcInfo log generation code.
> Supress Gcinfo-Debug Logs in Release build

- test/llilc_runtest.py
Add the --precise-gc option to llilc_runtest.py to test with precise GC.
> Add an option to test with Precise-GC

- Documentation/Debugging.md
- Documentation/Welcome.md
- Documentation/llilc-Coding-Conventions-and-Commenting-Style.md
- include/Jit/LLILCJit.h
- include/Jit/jitoptions.h
- include/Reader/reader.h
- lib/Jit/LLILCJit.cpp
- lib/Jit/jitoptions.cpp
- lib/Reader/reader.cpp
Modify LLILC options processing by adding the
following options:
* COMPlus_ALtJitExclude is a MethodSet. LLILC will only
attempt to compile methods which are in the COMPlus_AltJit
set, but not in the COMPlus_ALtJitExclude set.
* COMPlus_ALtJitBreak is a MethodSet. This is used
when running LLILC under the control of a debugger.
It causes a "break" message to be written for
matching methods when the method is about to be
jitted. The method is written from the
LLILCJit::compileMethod method in file
llilc\lib\Jit\LLILCJit.cpp. The user must put
a breakpoint on the statement that writes
out the message in order to actually get a
break.
* COMPlus_ALtJitMSILDump is a MethodSet. The MSIL for
methods in the set is dumped before JITTING the
method.
* COMPlus_ALtJitLLVMDump is a MethodSet. The LLVM …
> Cleanup and improve LLILC debug facilities

- lib/Reader/readerir.cpp
The call to getting a DataLayout object changed in LLVM. Update LLILC to
use the new call.
> Change getDataLayout to createDataLayout

- lib/Reader/readerir.cpp
A line was 81 characters long so needed to be broken.
> Fix formatting error.

- include/Reader/abisignature.h
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
jmp is implemented as a call marked with musttail followed by a ret.
If the caller has a secret parameter we need to pass it to the jmp call
because the signature and the calling convention of the caller and
the musttail call must match. To accommodate that a parallel
LLVM change modifies CLR_SecretParameter calling convention
to make the secret parameter the first pointer-sized parameter
(still passed in R10) rather than a parameter passed with a
"CLR_SecretParameter" attribute.
All indirect parameters are passed as they come to the caller, without
copying them to the current frame.
Indirect result parameter is typed as a managed pointer in a jmp call
because we type indirect result parameter for the caller as a
managed pointer.
Closes #192.
> Implement translation of jmp msil instruction.

- utils/ccformat.py
1) Add -fExceptions argument so that functions with throw build OK with clang.
2) Disable the [misc-unused-parameters] temporarily since there
are many failures for this rule.
[https://github.com/dotnet/llilc/issues/726]
> Fix clang-tidy invocation in ccFormat

- include/Jit/EEObjectLinkingLayer.h
- include/Jit/LLILCJit.h
- lib/Jit/EEMemoryManager.cpp
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
Process all relocations in ObjectLoadListener::recordRelocations.
Fix an issue with read-only section alignment: make sure Constant
pools have a 16 bytes alignment.
Create a copy of ObjectLinkingLayer (EEObjectLinkingLayer) so that
we can suppress relocation resolutiotion by LLVM. Lang Hames is
likely to re-design ObjectLinkingLayer in the future to allow more
control over relocations. When that happens we should be able to get rid
of our copy.
Closes #699.
Closes #700.
> Support for ngen-ing of methods with switches and floating point instructions.

- include/Jit/jitoptions.h
- include/Reader/options.h
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Jit/jitoptions.cpp
- lib/Reader/abi.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Support System.Numerics.Vector with fixed size.
Represent Vectors like LLVM::<float * VectorSize>.
Change getfield and storfield behavior to avoid memcopy and use Vector LLVM specific assessors.
Support binary, unary, ctors operations.
> Simd initial pull request

- utils/ccformat.py
In the lab, we aren't seeing any output from ccformat. To confirm that
it is being run, we want to print out the command line arguments that
were passed to ccformat.py.
> Print command line arguments passed to ccformat

- test/exclusion.targets
Add exclusion for the four tests failing with Statepoints Inserted
when using conservative GC.
The condition in exclusion.targets is based off the
Complus_InsertStatepoints environment variable, taking advantage of
the fact that the lab job sets this variable on the command line
before invoking llilc_runtest.
> Test with Statepoints: Add exclusions for failing tests tests

- lib/Jit/LLILCJit.cpp
Set DataLayout on newly created module so that there's agreement between the TargetMachine and the Module.  This check is forthcoming in the LLVM merge.
@erozenfeld @adiaaida
> Update ModuleDataLayout from TargetMachine

- lib/Jit/LLILCJit.cpp
The lowering of the blockaddress intrinsic (which EH lowering will make
use of) invovles relocations in .text with type ST_Debug.  Change the
exclusion in LLILC's relocation processing to check for section name
.debug rather than relocation type ST_Debug.
Also, LLVM expects the data in the image to be added to the symbol address
when a relocation is applied, but the EE's recordRelocation simply
overwrites the data in the image.  Compensate by looking up the data in
the image and adding it to the target value passed to recordRelocation.
> Handle more relocations

- test/llilc_roslyn_stage.cmd
- test/llilc_run.py
test/llilc_run.py is a general utility for running applications
with LLILC as the JIT. The test/llilc_run.pyproj  and
test/llilc_run.sln are useful for testing it from within
Visual Studio (requires Python Tools for Visual Studio).
test/llilc_roslyn_stage.cmd is a batch script that
will create a bootstrap stage directory for Roslyn
from the existing Roslyn binaries. It then builds
Roslyn using those binaries.
> Add support for building Roslyn (and other apps) with LLILC.

- include/GcInfo/GcInfo.h
- lib/GcInfo/GcInfo.cpp
- lib/Jit/LLILCJit.cpp
GcInfoEncoder needs to find the distance (offset) of the
Function entry point to the start of the code section.
For this, it calculated the diffrence between the HotCodeBlock
and the function address reported in __llvm_stackmaps.
However, in an Ngen/AOT build, the FunctionEntry address
recorded in LLVM's StackMap are post-relocation offsets.
Therefore, it cannot be compared to the Start of the CodeBlock
allocated during compilation.
This change fixes this bug by using non-relocated code-block
address for both function-entry and code-block-start.
Fixes #743
> GcInfo: Fix Offsets for NGEN

- test/llilc_roslyn_stage.cmd
- test/llilc_run.py
llilc_run.py is used to run managed applications using LLILC
as the JIT. llilc_run.py takes command line arguments and the
managed application being run may also take command line
arguments. We must avoid conflicts between these command line
arguments.
The previous version of llilc_run.py attempted to avoid
conflicts between the arguments supplied to llilc_run.py and
the applications command line arguments by 
making llilc_run.py's command line arguments all start with
'llilc-' and by avoiding abbreviated forms. This made
the script less convenient to use and also did not provide
an absolute guarantee of no conflicts.
This change makes use of a common feature of open source
programs that invoke other programs. That feature is using
'--' to separate the parameters of the invoking program …
> Improve usability of llilc_run.py

- Documentation/Contributing.md
This change adds links to Contributing.md to the more up-to-date
versions of clang-format and clang-tidy
> Add links to Contributing Guide for formatters

- test/exclusion.targets
Another test run with statepoints inserted hit failure noted in Issue #735.
This cause the nightly testing to fail:
http://dotnet-ci.cloudapp.net/job/dotnet_llilc_insert_statepoints_nightly/95/console
So, exclude the test until #735 is fixed.
> Exclude a test in INSERTSTATEPOINTS run.

- include/Reader/readerir.h
- lib/Reader/GenIRStubs.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
- test/llilc_run.py
LLILC was already allowing int32 to int64 comparisons
for the opcodes that produce a boolean result.
But the code that adjusted comparison arguments was
only partly duplicated for branch comparisons.
This change factors out the common code that
adjusts comparison arguments so that boolean result
comparison and branch comparison are treated consistently.
With this change test
JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b91223,
which was failing with an assertion failure is now
able to compile the ILGEN_0x9c0b37ec.Method_0xa1f09b04
method. The test still fails later, because the tests
correct execution throws an overflow exception which
LLILC is not yet prepared to catch.
This change also includes two other small changes:
The MSIL dumps were being written directly to stderr
rather than going …
> Allow int32 to int64 comparisons in branches

- utils/ccformat.py
Fix one of the flags passed to clang-tidy to use the correct hyphen.
> ccFormat: Fix a Hyphen

- include/GcInfo/GcInfo.h
- include/GcInfo/Target.h
- lib/GcInfo/GcInfo.cpp
- lib/Reader/CMakeLists.txt
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
CoreCLR requires that we identify whether a method's frame is
FP or SP based. This is inaddition to reporting the reference pointers
for the slots representing liveness. So, this change reports the
StackBasePointer in the GcTable header.
To facilitate the above, the GcInfo encoding functions are
restructured to be per-function routines.
Fixes #758.
> GCTables: Report StackBasePointer.

- test/exclusion.targets
After the fix to #637 forty more tests now pass, so remove
these from the exclusion.targets. In additional one other
exclusion (JIT\Directed\coverage\oldtests\arrgetlen.cmd)
was for a non-existent test so also removed it.
Checked compiler testing passed locally with this updated
exclusion.targets list.
> No longer exclude tests now passing as a result of #637 fix.

- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
Update to the changed section API.  Done to match the LLVM merge.  Also includes work around for degenerate block uninitialized data.
> LLVM merge fixes

- Documentation/Debugging.md
- include/Jit/jitoptions.h
- lib/Jit/jitoptions.cpp
- test/llilc_run.py
- test/make_sln.py
The changes makes the following improvements to the
LLILC debugging facilities:
1. A make_sln.py script is added which can be used to create
a Visual Studio 2015 solution that can be used to debug
a managed application using LLILC. Optionally the
script can invoke Visual Studio on the created solution.
The handles setting up all the required environment
variables for making LLILC the alternate JIT.
2. A --windbg-and-args option was added to the
llilc_run.py script to enable debugging the
application being run using windbg.
3. In order to ensure that empty values for
LLILC configuration variables are equivalent to
unspecified environment variables, the
code that LLILC uses to check some configuration
variables was refactored to require that
the feature is only enabled if the variable
is …
> Additional LLILC debugging aids

- utils/ccformat.py
If formatting fails, we would like to have a link to the
clang-format.exe that is being used in the lab so users can easily find
what their code will be tested against.
> Add link to clang-format.exe to ccformat

- lib/Reader/readerir.cpp
GcInfo encoder doesn't yet report certain data in the
GCInfo headers.
1) Generic Context slot: #766
2) Security Object Slot: #767
3) GSCookie slot: #768
This change adds exclusions for functions containing (1) and (2)
when compiling for Precise GC.
There is no exclusion for (3) because stack protection checks are
yet to be implemented in LLILC #353
> Precise GC: Add NYIs for functions with missing info

- include/Jit/compiler.h
ORC Compiler functor was using a API that had been deleted in LLVM.  Call is no longer needed and so is removed.
> Update LLILC ORC Compiler

- lib/Jit/LLILCJit.cpp
We should not assume that the function is starting at address 0. Since
we do grab that info, we should make it explicity that locals are in
scope from the starting address of the function through the starting
address + size.
> Don't assume start address is 0 for local debug info

- test/llilc_runtest.py
Add an option to run with Statepoints inserted, but with
Conservative GC mode.
Without this option, the lab used to set certain COMPLUS
variables outiside the script, which caused constraints
for private submissions of nightly jobs like Statepoint job.
The current GC settings are:
Complus_GcConservative=1 (default)
-s    Complus_InsertStatepoints=1 and Complus_GcConservative=1
-p    Complus_InsertStatepoints=1
> llilc_runtest: Add an option to run with Statepoints inserted

- test/exclusion.targets
Some of the failing excluded tests that formerly were excluded
because of issue #637 still fail even though issue #637 has
been fixed, because they throw exceptions. Change the issue
number for these to #13. I verified in the debugger that
these tests do in fact throw an exception (when compiled with
Ryujit on the CoreClr).
In addition this change deletes some exclusions for tests that
no longer exist. Also one test had "13(" as its issue, so I
fixed that so it is "13".
> For former #637 tests that throw exceptions, change to issue #13

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
If a block terminator is
br i1 %6, label %7, label %7
and the operand stack is not empty,
we'll create a PHI instruction in the successor block with an undef operand:
; <label>:7                                       ; preds = %2, %2
%8 = phi i32 [ %3, %2 ], [ undef, %2 ]
...
; <label>:9                                       ; preds = %7
%10 = add i32 %8, 3
We never update the undef in this case.
llvm::removeUnreachableBlocks calls llvm::constantFoldTerminator
and optimizes the br instruction above so that the above code becomes
br label %5
; <label>:5                                       ; preds = %4
%6 = add i32 undef, 3
which is a problem. This was causing 6 of our tests to fail.
The fix is to update all PHI operands corresponding to a predecessor,
not just one.
Closes #785.
> Fix PHI update logic.

- lib/Jit/LLILCJit.cpp
For communicating debug locals to the CLR EE, we want to make sure that
the starting address for the current function matches that of the
Subprogram DIE. In the case where we have multiple function symbols in
one module (GC Statepoints, funclets), we want to make sure that we are
passing to the EE locals that belong to the actual function (ie, not the
gc.safepoint_poll function). This change extracts the Subprogram DIE's
low pc (start address) and compares it to the symbol's start address. If
the two are not the same, it returns without collecting local debug
info.
> Make sure subprogram addr and function addr match

- lib/Jit/EEMemoryManager.cpp
- lib/Reader/readerir.cpp
@gc.SafepointPoll() function is never expected to be called
at runtime, so we can save generating unwind information for it.
PlaceSafepoints phase inlines the contents of @gc.SafepointPoll()
at all gc-polling locations.
EEMemoryManager::registerEHFrames() is written with the assumption
that there's only one function per module. This assumption is not
true when ruin with COMPLUS_InsertStatepoints=1 because of the
addition of the @gc.SafepointPoll() function. This resulted in
reporting incorrect UnwindInfo to the runtime.
This limitation needs to be fixed for FunctLets (an orthogonal issue).
But can be circumvented for the SafepointPoll function by marking it
with the NoUnwind qattribute.
This change also adds a check in the EEMemoryManager to check that
UnwindInfo is actually generated for …
> Mark @gc.SafepointPoll() as NoUnwind

- test/exclusion.targets
Closes #601.
One test now passes, the rest fail with issue 13. Most of the failing tests had an orphaned entry for 601 mentioning the old .cmd file name and a new entry already updated with issue 13.
> Reclassify and clean up the 601 exclusion entries.

- test/exclusion.targets
Closes #596.
One test passes, the remaining have EH and so now are excluded under issue #13.
> Reclassify the excluded tests from issue 596.

- CMakeLists.txt
When using RelWithDebInfo instead of Debug/Release, we failed to find llvm-config file.
The fix is to simply add such case as well.
> Fix for llilc build out of llvm tree

- test/exclusion.targets
Closes #462.
One test requires EH, one no longer exists, and the rest require large amounts of memory. Opened #794 for those.
> Reclassify tests with exclusion issue 462.

- test/exclusion.targets
Closes #487.
One test passes, the other two require eh and so are excluded via issue #13.
> Reclassify failures with exclusion issue 487.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
Closes #643.
When boxing, pass the size instead of the CorType into the argument helper, so if the box type is a value type we have the size available.
Enable the test that was failing with the assert.
> Fix assert in box codegen.

- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
Closes #789. Closes #797.
For #789, when merging stack states, if the types being merged
are int32 and native int, keeps the first type in order to
conform to the ECMA standard. This fixed 8 tests.
For #797, if a switch has a selector whose type is not i32,
fix up the types of the case values to match. This fixed
two tests.
> Fix #789 and #797

- lib/Reader/readerir.cpp
- test/exclusion.targets
This fix handles function pointers in calls by using
bitcast to convert to pointer to function type,
rather than inttoptr as is done if the target is a
pointer-sized integer.
Two of the tests were originally classified as #637
but after that was fixed became #633.
With this fix 11 tests pass. 5 tests were found
to no longer exist. 4 tests still fail with
thrown exceptions and are given issue #13.
> Fix issue #633

- test/exclusion.targets
Closes #645.
Issue #645 was "Investigate various non-obvious failures in the IL tests".
Twenty-two tests were excluded because of issue #645.
The investigation did not reveal any new passing tests. The tests were
disposed as follows:
* Test found to no longer exist: 6
* Tests throwing exceptions (issue #13): 11
* Tests using unsupported variable-length argumenet lists (issue #52): 4
* Test failing because of float of integer conversin problem
(new issue #808): 1
> Resolve Issue #645

- test/exclusion.targets
- test/make_sln.py
Closes #634.
I reassessed the tests formerly excluded for issue #634.
Of these, two no longer exist and the remaining 8 pass.
So remove them from the exclusion list.
I also corrected one typo in a comment in the make_sln.py
script.
> Resolve issue #634

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
- test/exclusion.targets
Closes #644.
Create the finally dispatch IR a bit more flexibly -- either when the reader first sees the endfinally, or first sees a leave.  Otherwise we risk leaving the finally IR dangling outside of any basic block.
The test case now fails because of EH, so reclassify as blocked by issue #13.
> Handle cases where the finally lexically precedes the try.

- lib/Reader/readerir.cpp
- test/exclusion.targets
Closes #641.
Ecma-335 III.4.19 says the argument to `mkrefany` must be type `&` or `native int`, but it appears traditional that arbitrary ints are allowed. Tolerate this.
Enabled the one blocked test that now passes.
> Tolerate integers in mkrefany.

- utils/ccformat.py
Set Clang's -fmsc-version to 1800 or 1900 based on the
toolset version in the dev-environment.
Verified that ccFormat works for VS 2015.
> ccFormat: Add VS2015 support

- include/Jit/LLILCJit.h
- include/Reader/options.h
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Jit/jitoptions.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Add supporting for generic SIMD Vectors,
represent System.Numberics.Vector<T> with llvm::Vector,
support intrinsics for binary operations (arithmetic, bit), unary (sqrt,
abs), constructors, getCount.
IsHardwareAccelerated returns true for all types.
> add supporting for generic SIMD Vectors

- test/exclusion.targets
Closes #635.
All four of the tests excluded for issue #635 throw
exceptions as part of their normal execution.
So change the issue number for these to #13
until LLILC implements catching exceptions.
> Resolve issue #635

- test/exclusion.targets
Remove four tests from exclusion.targets,
now that the problem causing #735 is fixed.
Fixes #735.
> InsertStaetpoints Run: Remove some test exclusions

- lib/Reader/reader.cpp
If asked to verify we will currently check and break of out phase 2 of the
reader early. This will cause a BB to be processed later without a
terminator causing a crash.
> Adding NYI if verifying to avoid degenerate Blocks

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Create a Block -> Region map in the first pass by paying attention to
region boundaries as we advance through the IL, and maintain it as new
blocks are added in the second pass by preserving it when splitting blocks
and such.
Expand the EHRegion struct to include fields that will be useful for
building EH flow.
Remove the setupBlockForEH method that is now superfluous.
Add a stub EnterRegion method to GenIR; this is where landing/EH pads will
be generated as the EH implementation comes online.
> Map BasicBlocks to EHRegion nodes

- CMakeLists.txt
- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- test/LLILCTestEnv.cmd
- test/llilc_run.py
- test/llilc_runtest.py
These changes implement jit features for ReadyToRun compilation.
The ReadyToRun overview is located here:
https://github.com/dotnet/coreclr/blob/master/Documentation/botr/readytorun-overview.md
It's a format that provides version resiliency on top of ngen.
These changes mostly follow what's implemented in RyuJit.
Special handling is done for the following operations:
* Type context creation
* Struct copy with write barriers: CORINFO_HELP_ASSIGN_STRUCT is not available for ReadyToRun
and is not used by RyuJit at all (it's considered inefficient). I implemented inline copy expansion.
* Field access
* isinst and castclass
* Class constructor insertion
* Static field address calculation
* Direct call target computation
* Indirect virtual call target computation
* Function pointer loading
* …
> Implement llilc support for ReadyToRun.

- CMakeLists.txt
- Documentation/Getting-Started-For-Linux-and-OS-X.md
- Documentation/Getting-Started-For-Windows.md
- Documentation/Setup-With-LLILC-Out-Of-LLVM-Tree.md
When cmake is "cross-compiling" LLVM (which means that the build-host
which LLVM will be built on differs from the build-target/compile-host
that LLVM will be built to run on [regardless whether the built LLVM is a
cross-compiler or not]), it uses a recursive cmake invocation targeting
the build-host to build some tools that LLVM uses in its build process.
Check the LLVM_TARGET_IS_CROSSCOMPILE_HOST flag that is set in these
recursive invocations, and skip adding LLILC targets when it is set; this
is fine to do because LLILC is not one of the tools that LLVM uses in its
build process, and is necessary because the recursive invocations do not
pass the WITH_CORECLR setting that LLILC requires.
This will allow configuring with LLVM_OPTIMIZED_TABLEGEN=ON (which
internally uses …
> Fix cross-compile cmake error

- lib/Reader/readerir.cpp
- test/exclusion.targets
The ECMA-335 spec says that for unchecked floating point to
integer conversion, that if there is overflow then the result
is unspecified. However for compatibility with other jits
we make the result more deterministic. If the target
bit size is less than 64 we first convert to i64 where overflow
is less likely. Then we truncate to the target bit size.
Closes #808 and allows test
\JIT\Regression\CLR-x86-JIT\V1-M10\b05617\b05617.cmd
to pass.
> Make float to int conversion more determined.

- test/exclusion.targets
New test case is intermitantly failing.  This change excludes the test in deference to the issue 833.
Test will be re-enabled after investigation.
> Exclude readytorun mainv2 test

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
This change revises the flow graph edge iterator implementation to reduce memory leaks. The iterator is now a stack allocated object that frees its resources when destructed. I've used move-copy semantics to avoid needing to copy the iterator payload when the iterator itself is copied.
Unfortunately it's not possible to eliminate the allocations entirely without either edges having object identity (which they don't in LLVM) or a deeper reworking of the base/client contract, or by using the `Impl` variants directly in the reader code. For now I'm content to just not leak.
I ran this through a couple of the huge allocation cases but could not measure any significant impact.
> Rework flow graph edge iterators to reduce leaks

- include/Reader/reader.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
This is the initial step in fixing jit-related memory leaks. It partially addresses #794. Using the debug CRT (which entails various hacks too ugly to commit) this set of changes gets rid most of the direct leaks from the jit. Most simple methods now leak ~2K when jitted, down from ~50K. We can also now process the various huge cases that blocked us.
I plan to subsequently rework most of this to use automatic reclamation.
Free up EH region and related info when done reading. Make sure we track the all region list to enable this (the code was set up to do this at one time, but when we went to LLVM naming conventions we introduced a local shadow). Streamline processing of raw eh clauses a bit.
Free up "initial" reader stacks when done reading.
Free up node offset array and related when done …
> Fix various memory leaks in the jit

- lib/Reader/reader.cpp
The temporary vector that was created is reallocated instead of resized.
Small change to resize the vector to avoid any possible memory leaks due
to unsafely reallocating the vector.
> Removing unnecessary temporary.

- lib/Reader/readerir.cpp
- test/exclusion.targets
ReadyToRun mainv2 test has a series of subtests. One of them is TestGrowingStruct.
The scenario is that an app is ReadyToRun-compiled against a version of a struct in a lib.
Then two new fields are added to the struct and the lib is ReadyToRun recompiled.
Then we attempt to run the app without recompiling. What should happen in this case
is that the runtime should detect that the struct layout has changed and the pre-compiled
code for the method in the app is invalid and the method should be JIT-ed.
The reason that wasn't always happening was because we have per-thread caching of types.
Crossgen records structs that the JIT calls getClassSize for and that allows the runtime to do
the detection described above. In this case more than one method needed the info about
that struct but …
> Disable type caching across methods in ReadyToRun mode.

- test/exclusion.targets
Two tests time out because some loops take longer to run
with gc-probes inserted within loops.
We need to add an option to the CoreCLR test framework to
specify timeout factor (dotnet/coreclr#1541).
This change adds exclusion for the failing tests until the
above issue is fixed -- so that InsertStaetpoints job is green.
> InsertStatepoints: Add exclusion for a test that times out.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Note: this is a PR for a change to go into the EH branch.
Change the reader to generate catchpad/cleanuppad instead of landingpad:
- Catch handlers translate to catchpads with the token for the caught
exception type as an argument.
- Finally handlers translate to cleanuppads with no arguments.
- Fault handlers translate to cleanuppads with a single dummy argument to
distinguish them from finally handlers.
- Filter expressions get outlined into separate filter functions, and
their handlers get translated to catchpads with the filter function as
an argument.
The IR generated for finally/fault handlers currently fails verification
because the uses of cleanuppads on cleanuprets/cleanupendpads aren't
dominated by those defs; we'll ultimately want a cleanupcall operator, and
the near-term plan …
> Generate new WinEH representation in reader

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Note: this is a PR for code to go into the EH branch.
The main reader passes generate IR for finally handlers that reflects the
right semantics, but is ill-formed because the `cleanuppad` at the entry
of a finally doesn't dominate its uses at the exits from that finally
(because there is a side-entry for the non-exceptional paths through the
finally).
Add a post-pass (in `readerPostVisit`) that makes a separate clone for the
non-exception version of each finally handler, leaving the `cleanuppad`
def and uses well-formed on the exception-only path.
The long-term plan is to add a `cleanupcall` operator to LLVM that the
non-exceptional paths can use to target the `cleanuppad` directly (and
perform finally cloning as a subsequent optimization in many cases, but
without the need to introduce …
> Clone finally bodies

- test/exclusion.targets
Closes #638.
The test that was failing with issue #638 no longer fails.
Remote it from the exclusion.targets.
> Resolve issue #638 and update exclusion.targets

- include/Reader/reader.h
- lib/Reader/reader.cpp
Delegate constructor optimization is implemented via
CORINFO_HELP_READYTORUN_DELEGATE_CTOR helper
and is only available for non-virtual function pointers
resolved at compile time.
Closes #841.
> Enable delegate constructor optimization in ReadyToRun mode.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
- test/exclusion.targets
Closes #846.
Of the 23 tests that have ckfinite, 7 now are excluded because they throw exceptions.
> Implement ckfinite

- lib/Reader/readerir.cpp
- test/exclusion.targets
This addresses #821 and #499.
Exclude tests with varargs callees under dotnet/coreclr#1440. Also improve the NYI message to call out varargs differently than native conventions.
> Exclude tests with varargs calling convention

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Running the verifier before unreachable code removal would have caught
some of the bugs we had (e.g., #785).
Changes to pass the verifier:
* Add unreachable instruction in place of return during flow graph building.
Remove the unreachable when processing return instruction in the second pass.
* Type dummy switch selector as int32 so that there is no mismatch with types
of case values.
* Move DBuilder finalization to readerPostVisit to avoid invalid MDNodes.
Closes #849.
> Run verifier before unreachable code removal.

- lib/Reader/readerir.cpp
- test/exclusion.targets
Closes #592.
Allow an unmanaged pointer as the pointer value in a mkrefany, by casting it to a managed pointer.
> Handle unmanaged pointer types passed to mkrefany

- include/Reader/reader.h
- include/Reader/readerenum.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Delete a bunch of code left over from a previous EH tracking regime, which
we won't be using going forward.
> Remove vestigial EH/Region-related code

- include/Reader/readerir.h
- lib/Reader/abisignature.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Note: this is a PR for a change to go into the EH branch.
Lowering for filters (as filters) is going to lag behind lowering for the other handler types.  This is a change to have filters masquerade as catches in the meantime -- the catch encompasses both the filter and the filter-handler, with an explicit rethrows if the `filter portion returns 0.  This is not fully "as-is", because it effectively delays the evaluation of filter expressions from the first pass of unwinding to the second.  Aside from that, however, it is a faithful representation of filter semantics.
I've created a [gist](https://gist.github.com/JosephTremoulet/bd635de873e90de9b710) to show the effect of the transform.  It includes a [C# input](https://gist.github.com/JosephTremoulet/bd635de873e90de9b710#file-input-cs), …
> Translate filters to catches in reader

- CMakeLists.txt
- include/GcInfo/Target.h
- include/Jit/LLILCJit.h
- include/Reader/ophelper.def
- include/Reader/readerenum.h
- lib/GcInfo/GcInfo.cpp
- lib/GcInfo/GcInfoUtil.cpp
- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
For headers in "fixed" locations like the ones we get from the CLR, suppress CMake's desire to add cross-targeting prefixes.
Add some Arm64 register mappings for the GC info.
Fix warnings from Clang that were not caused by `-Wnon-virtual-dtor` or `-Wunknown-pragma`.
> Some retargeting support and warnings cleanup

- test/exclusion.targets
Until we have a chance to investigate exclude this new test from our testing.
Issue is tracked as #860
> Exclude new Interop test causing an assert in llilc testing

- lib/Reader/readerir.cpp
When compiling for Precise GC runtime, yield methods
that use pinned variables to the default JIT until #29 is fixed.
> Precise GC: Exclude Methods with Pinning

- include/Reader/readerenum.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
Addresses #865.
Make sure to use the relocated section for determining final addresses.
Skip some elf-specific sections that contain debut and unwind info when processing relocations.
> Some fixes for ELF relocation processing

- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
Unless FEATURE_VERIFICATION is enabled we will always verify methods.
> Removing verification NYI to always verify.

- lib/Jit/LLILCJit.cpp
- lib/Jit/jitoptions.cpp
Closes #866.
Casing of environment variables doesn't matter on Windows but does on Linux. Make sure we're consistently using `COMPlus` as the prefix and that the suffix is generally camel-cased. There are two classes of exceptions:
* `COMPlus_gcConservative` is specified that way by the CoreCLR.
* LLILC specific options (ones that the CoreCLR doesn't look for or care about) are generally all uppercased, eg `COMPlus_DUMPLLVMIR`.
> Change casing of options text to be more consistent and match CoreCLR

- include/Reader/reader.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
* Change rdrCallFieldHelper to return an IRNode: return Destination for
struct fields and the call instruction for others field types for
load. Return the call for store, but it is not used by store field.
* Add support for LoadField via helper: For struct fields, we want to
create a temporary IRNode, for all other types, we want to get a
nullValue of the field type.
* Add call to rdrCallFieldHelper for store field via helper.
> Add hooks for loadfield via helper and storefield

- include/Pal/LLILCPal.h
Closes #877.
Add __in_z to the set of suppressed annotations.
> Add suppression of new sal annotation in CLR headers

- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
Closes #865.
Elf relocations (at least on x64) carry the addend as part of the relocation.
Also skip looking at relocations the plain `.eh_frames` section.
Also for some reason I am seeing funny whitespace in existing checked in code. When I reformat this gets "fixed".
> Elf relocations include the addend as part of the relocation

- lib/Reader/readerir.cpp
Refany wil be handled like a normal struct, returned byref. While
__arglist will now throw an NYI because CoreCLR does not support it.
> Removing return refany NYI.

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
Use `llvm::removeUnwindEdge(BasicBlock*)` instead.
[small change to apply to EH branch]
> Remove `GenIR::removeUnwindDest(TerminatorInst*)'

- lib/Jit/LLILCJit.cpp
PR  Microsoft/llvm#92 removes the parametrization of
RewriteStatepointsForGC phase on whether the base-pointers
of all live gc-pointers must be computed.
This change adapts LLILC code to use of new API.
> ReWriteStatepointsForGC: Compute base-pointer

- lib/Reader/readerir.cpp
Delay it until after we've determined if the method is varargs.
> Reorder varargs NYI check

- lib/Jit/LLILCJit.cpp
Explicitly set the module's debug info version to the current one.
Without this, writing out bitcode from LLILC and reading it back in will
strip the debug info, because the LLVM parsers check for the debug info
version and strip debug metadata if it does not match the version that the
parser was built with.
> Set debug info version module flag

- lib/Reader/readerir.cpp
This change updated interlockedCmpXchg and interlockedIntrinsicBinOp:
* In interlockedCmpXchg, the Exchange IRNode and Comparand IR node must
have the same type, however, we can have cases where Exchange comes in
as a pointer. If Exchange is a pointer, we want to cast it to the same
type as Comparand.
* In interlockedIntrinsicBinOp, we call CreateAtomicRMW, which assumes
that Arg1 is a pointer to the type of Arg2, however, we have instances
where Arg1 is a pointer to a pointer of the type of Arg2, so we need
to cast it to a pointer, like we do with Destination in
interlockedCmpXchg.
> Fix types of IRNodes in interlocked functions

- CMakeLists.txt
- include/Reader/reader.h
Suppress warnings about virtual dtors since the CLR header patterns are not clean.
Disable warnings about unknown pragmas since we use #pragma region.
Disable warnings about covered switch defaults since we use this to detect upstream enum changes.
Add a missing dtor to ReaderStack.
> Fix or suppress warnings building on Linux.

- test/llilc_roslyn_stage.cmd
- test/llilc_run.py
With these changes the lab job to run Roslyn building Roslyn
using LLILC succeeds.
llilc_roslyn_stage.cmd changes:
- Previously llilc_roslyn_stage.cmd was using c:/Python34,
but that is no longer installed on lab machines. The script
that it invokes will work with either Pythone 3.4 or 2.7 so
just use the Python on the path.
- Add buildtype as an argument to llilc_roslyn_stage.cmd
so it will work with debug, checked, or release builds.
- Revise for new Roslyn strategy for running on coreclr.
- The Roslyn analyzers sometimes throw task cancellation
exceptions. Since LLILC cannot handle these yet,
inhibit their use.
llilc_run.py changes:
Use lists to accumulate arguments for the command.
rather than strings. Using strings seems to cause
problems on some machines (observed for Windows Server …
> Update llilc_roslyn_stage.cmd and llilc_run.py scripts

- include/Reader/reader.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
It's legal MSIL for a protected region's handler(s) to precede it, but
fgSwitchRegion wasn't expecting this.  Add a property of try regions that
indicates which of the try region itself or its handlers is lexically
first (called its "EntryRegion"), computed during EH Region Tree
construction, which fgSwitchRegion can use to make sure it calls
fgEnterRegion exactly once for each try, and before switching to any
handler of the try.
> Account for try regions that follow their handlers

- lib/Reader/readerir.cpp
This parameter was unused and so was removed from the method in r250374.
This requires a paired change to the MS branch of LLVM; http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/1188/console has the test with both changes together.
@adiaaida or @russellhadley PTAL.
> Stop passing a DIFile to createSubroutineType

- include/Jit/jitoptions.h
- include/Reader/options.h
- include/Reader/readerir.h
- lib/Jit/jitoptions.cpp
- lib/Reader/readerir.cpp
- test/llilc_run.py
This will make it easier to triage failures due to unsupported EH
behavior.
Also add a setting that overrides this behavior to facilitate EH testing.
> Insert failfast calls at exception handler entries

- test/llilc_runtest.py
This mirrors the --eh flag of llilc_run.py; it stops LLILC from inserting
failfasts in handler entries, so that the generated handler code can
execute.
> Add --eh flag to llilc_runtest.py

- test/exclusion.targets
Closes #903.
This is a bit of a hack, but it should get us back up off the ground.
Once EH lands we won't need most of these anyways.
> Update exclusion file to handle new paths for tests

- include/Jit/LLILCJit.h
- include/Reader/readerir.h
- lib/Reader/readerir.cpp
This fixes Linux build when using gcc. Some of name space qualifier are explicitly added.
> Fix for build break in Linux

- lib/CMakeLists.txt
- lib/ObjWriter/CMakeLists.txt
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
- utils/ccformat.py
This is a standalone object writer (dll/so) that can wrap code/relocation using LLVM MC layer.
So this tool can be plugged into other either native or managed tool easily.
The following APIs are provided.
InitObjWriter
FinishObjWriter
SwitchSection
EmitAlignment
EmitBlob
EmitIntValue
EmitSymbolDef
EmitSymbolRef
Since the tool itself is very simple, adding an explicit test is skipped.
But we still validate the build of this tool.
Packaging this tool work will follow.
> Object Writer

- include/GcInfo/GcInfo.h
- lib/GcInfo/GcInfo.cpp
- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
The EE DebugInfoManager requires the Jitted method to start at
the beginning of allocated Code block.
Therefore, this change moves gc.safepoint_poll() from the
beginning to the end of the module.
> Insert gc.sagepoint_poll() after the real Method

- CMakeLists.txt
- lib/GcInfo/GcInfo.cpp
- lib/Jit/jitoptions.cpp
- _DEBUG was not being defined when CMake was invoked without an explicit
build type. The build now defaults to debug unless otherwise specified.
- A couple of GC-related types needed global namespace qualifiers to avoid
name collisions.
- There were various const-cast related issues that needed resolution.
> Fix some Linux build breaks.

- lib/ObjWriter/.nuget/Linux/Microsoft.Dotnet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/Microsoft.Dotnet.ObjectWriter.nuspec
- utils/make_package.py
Added nuspec file to package object writer.
For now instead of creating package step into Cmake build, I provided a standalone python script which should run in any platform.
It takes target folder and nuspec file to create a package out of it.
> Packaging object writer

- lib/Jit/LLILCJit.cpp
CodegenPrepare's gc-opt turns gc.relocate for derived pointers
into GEP from the relocated base-pointer.
However, this optimization seems to assume that the base-pointer's
gc.relocate always appears before the derived pointer's gc.relocate.
However, RewriteStatepointsForGC phase does not enforce this, which
leads to an incorrect transformation.
So, disable the optimization until this issue is fixed.
Further details: Issue #914
Fixes #911
> Disable CodeGen prepare GcOpts

- include/Reader/readerir.h
- lib/Reader/readerir.cpp
This lowers directly to the CORINFO_HELP_RETHROW helper call.
Closes #70.
> Implement rethrow operator

- test/exclusion.targets
This change also modifies the form of exclusions in the exclusion.targets
file.  Because of a recent change to the testing infrastructure each
test project will have its binary and cmd in a distinct directory even
if its source was in the same directory as other test projects. Thus
to exclude a test it is sufficient to give the path to the directory
contaning its cmd file, followed by "\*". The root name of the cmd
file will be the same as the subdirectory name so there is no need to
repeat it.
> Exclude a couple of tests that use vararg methods.

- test/llilc_checkpass.py
llilc_checkpass.py has been enhanced to do a more complete
comparison between a target test run and a baseline run.
Reports are provided of the failing tests, the methods that
failed, and the reasons they failed. A variety of summaries
are provided.
In addition, llilc_checkpass.py can now operate without a
baseline test run. In this case the target run is still
analyzed and failures reported.
> Enhance llilc_checkpass.py to report failure details.

- test/exclusion.targets
This can time out with non-statepoints runs too; for example, it held up
the last FI from LLVM.
> Make b28158 test exclusion unconditional

- include/Jit/EEObjectLinkingLayer.h
- lib/Reader/readerir.cpp
Three changes in the next FI require changes to LLILC sources, which are bundled up here.
This will need to be committed in tandem with Microsoft/llvm#113.
@AndyAyersMS PTAL.
> Updates for LLVM FI signature changes

- test/exclusion.targets
This is a new test which is failing in our CI jobs.
Issue #927 is opened to investigate.
> Add exclusion for StructABI test

- test/exclusion.targets
A number of the EH-related tests can now pass (with conservative GC).  The
ExecuteHandlers configuration is still off-by-default since it's not yet
compatible with precise GC (and there are known errors with nested funclet
frame setup, and unknown errors in the 58 exclusions left unconditional),
but this change makes the exclusions for EH tests that work with precise
GC conditional on the ExecuteHandlers config flag so that we can start
tracking the progress of that configuration in the lab.
> Conditionalize 691 exclusions on ExecuteHandlers

- test/exclusion.targets
JIT/Methodical/cast/SEH/_speed_dbgthrow and _speed_relthrow still
sometimes fail under ExecuteHandlers; exclude them unconditionally.
> Make two test exclusions unconditional

- test/exclusion.targets
In preparation for the addition of a new test,
JIT\Directed\gettypetypeof\gettypetypeofmatrix\gettypetypeofmatrix.exe,
add an exclusion for it. The test fails if LLILC's
COMPlus_ExecuteHandlers is not set, but passes if it is, so
add the exclusion to the part where it is not set.
> Exclude gettypetypeofmatrix test if eh is not enabled.

- lib/ObjWriter/.nuget/Linux/Microsoft.Dotnet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/Microsoft.Dotnet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
This supports for emitting frame info for Windows.
Basically pdata/xdata is constructed like C++ to allow call stack dumps.
EH table itself is not populated yet since EH model is not determined.
> Emit frame info in Object writer

- CMakeLists.txt
- include/Reader/abi.h
- include/Reader/abisignature.h
- lib/Reader/abi.cpp
- lib/Reader/abisignature.cpp
- lib/Reader/readerir.cpp
Most of the work here involves adding support for aggregate arguments
that are represented as multiple primitive and aggregate arguments
that are represented as LLVM 'byvalue' arguments (i.e. LLVM arguments
with the 'byvalue' attribute). The former are used for IL by-value
struct arguments that must be passed in multiple registers; the latter
are used for by-value struct arguments that must be passed on the
stack. All arguments are classified as do enregister/do not
enregister using the interface provided by CoreCLR.
> Add support for the SysV AMD64 ABI.

- lib/GcInfo/CMakeLists.txt
LLVM change r252796 (git hash f805775e) reworked llvm/IR/Attributes.h so
that it now #includes a generated .inc file.  GCInfo.cpp transitively
#includes Attributes.h, so make it depend on the intrinsics_gen target
(which includes the generation of the .inc file)
> Make GcInfo lib depend on intrinsics_gen

- lib/ObjWriter/.nuget/Microsoft.Dotnet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.linux-x64.Microsoft.Dotnet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
This basically emits two tables.
One is for file name tables (along with index table).
The other is for native offset to source location info.
Adapted CodeView emission logic from LLVM mainline. Ideally this code should be refactored to be shared, which I will follow-up.
Nuget package version (and name for linux) is updated.
> Emit DebugLocInfo/DebugFileInfo in ObjectWriter for Windows

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- utils/make_package.py
Add support for redirection package using json.
Add individual nuspec for each platform.
Change local script to handle json file.
Note this doesn't affect any CIbuild but it is used for a post-process to create packages.
> Formalize object writer package names.

- test/exclusion.targets
Exclude tests that fail because LLILC does not yet
support tail call.
> Exclude tests failing because of tail call.

- test/exclusion.targets
JIT\Methodical\structs\systemvbringup\structinregs is a new test that
fails with LLILC.  Exclude it under issue 927 since it's testing similar
functionality as the test already excluded for that.
> Exclude new coreclr test

- include/GcInfo/GcInfo.h
- lib/GcInfo/GcInfo.cpp
PSPSym is used to find the frame when a GC occurs during execution of an
exception handler, and WantReportOnlyLeaf tells the GC that the leaf
funclet will report the live variables for the entire function.
> Report PSPSym and WantReportOnlyLeaf to GC

- Documentation/Debugging.md
- test/LLILCEnv.ps1
- test/llilc_run.py
- test/llilc_runtest.py
- test/make_sln.py
The issue in CoreFX that lead to us needing to run tests in code page 65001 is long since fixed. So remove the chcp from our test scripts and docs.
Closes #12.
> We don't need to chcp anymore

- .clang-format
Closes #953.
We might want to support this someday, but right now sorting includes per this rule breaks lots of stuff.
> Don't sort includes

- lib/Reader/reader.cpp
We were seeing two different entry point addresses for some methods.
LLILC will insert an explicit null check for calls in the cases that require one, so always request the non-null entry point for a method. Otherwise we  need to (potentially) keep track of the two entry point addresses for each function, and make sure the right one is used at each call site.
This closes #957 and should also fix #951.
> Always ask for the non-null entry point for a method

- include/Jit/LLILCJit.h
- test/exclusion.targets
Recent CoreCLR changes added different build flavors, update excludes accordingly.
> Update excludes to handle some renamed and adjusted tests

- test/exclusion.targets
Add exclusions corresponding to tests added to
coreclr on core PR #2220.
Tests that did not fail when LLILC EH was enabled
were put into the corresponding section of the
exclusion file.
> Add exclusions for new coreclr tests failing on LLILC

- test/exclusion.targets
Anticipatory pending merge of dotnet/coreclr#2271. Note these fail even when ExecuteHandlers is set.
> Exclude SIMD tests that require EH

- lib/Jit/LLILCJit.cpp
- test/LLILCTestEnv.cmd
We are seeing timeouts in the lab that seem likely to be caused by asserts raising error dialogs. Tell the CRT we want all assert output to go to stderr instead.
Closes #584.
> Suppress error popups from asserts

- test/exclusion.targets
- test/llilc_run.py
- test/llilc_runtest.py
With this set of four tests excluded, LLILC no longer skips any methods in the 3874 tests that remain.
> Exclude some varargs tests, suppress popups in local testing

- test/exclusion.targets
A new batch of tests is about to be added to CoreClr.
This change adds exclusions for those that fail on
LLILC even though they pass on RyuJit.
Tests that fail without EH enabled for LLILC but that
pass with EH enabled are given issue #13.
The remainder are given issue #970 for later
triage.
> Add exclusions for tests about to be added to CoreClr.

- test/exclusion.targets
Started in on reclassifying the #970 errors. Some tests now pass, some pass with EH, others now have more specific issues to track why they fail. Still a bunch more to work through as well.
Also excluded a few varargs tests, so that for the tests that do run, LLILC does not skip any methods, and normalized all the varargs exclusions to reference dotnet/microsoft#1440.
> Refine error classifications

- test/exclusion.targets
Was causing the rolling CI to fail with skipped varargs methods.
> Fix bad exclude syntax

- include/CoreDisTools/coredistools.h
- lib/CMakeLists.txt
- lib/CoreDisTools/.nuget/Microsoft.DotNet.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/toolchain.win7-x64.Microsoft.DotNet.CoreDisTools.nuspec
- lib/CoreDisTools/CMakeLists.txt
- lib/CoreDisTools/coredistools.cpp
- lib/CoreDisTools/coredistools.exports
This change adds CoreDisTools -- a library containing
LLVM disassembly tools for CoreClr to LLILC repo.
Currently, the library supports instruction-wise
disassembly API required for implementing GcStress.
coredistools.h -- the export/import header
coredistools.cpp -- the implementation as a wrapper around
LLVM disassemblers to suite the required API.
This change also adds code to package the library into a
NuGet package.
> Add CoreDisTools Library

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
- test/exclusion.targets
LLVM has streamlined the representation for funclet-style EH somewhat, by
pulling the dispatch aspect of catchpad out into a separate catchswitch
instruction, and by explicitly annotating EH pads with their enclosing
parents, obviating the need for endpads.
Update LLILC to generate catchswitch, emit the enclosing pad linkage, and
stop generating endpads.
Also update finally cloning accordingly.
> Update LLILC to generate new funclet EH IR

- lib/ObjWriter/objwriter.cpp
LLVM change r256203 (git hash 56afa6e6) added the
IncrementalLinkerCompatible flag to createMCObjectStreamer.  Update our
usage to pass the conservative value, true.
> Pass extra argument to createMCObjectStreamer

- test/exclusion.targets
Timeouts seem to have started with a recent LLVM FI (Microsoft/llvm#127).
> Exclude four tests that are timing out

- test/exclusion.targets
31 new coreclr tests are failing with llilc -- exclude them, tracked by
issue #993.
3 tests failed last night's automated FI -- exclude them also, tracked by
issue #994.
> Exclude failing tests

- test/exclusion.targets
Underlying LLVM issue was fixed by r256730 and that has now FI'd to our branch.
Closes #990.
> Undo excludes of tests that were timing out

- include/CoreDisTools/coredistools.h
- lib/CoreDisTools/coredistools.cpp
On X86, LLVM disassembler does not handle instruction prefixes
correctly -- please see LLVM bug 7709.
The disassembler reports instruction prefixes separate from the
actual instruction. In order to work-around this problem, we
continue decoding past the prefix bytes.
Instead of checking for LLVM Opcodes (which are subject to change
after any checkin), the check is performed using Machine opcode.
The tool also has a checker to verify our understanding of the way
X86 prefix bytes are decoded by LLVM. It is possible to add a
cross-verification wrt LLCM-opcodes, but the code will need
frequent updating.
> CoreDisTools: Handle disassembly of X86 Prefix bytes.

- lib/ObjWriter/objwriter.cpp
- test/exclusion.targets
https://github.com/dotnet/coreclr/commit/8353857ecea0fb4410d72fcf69aeb55fb09feef5 enabled this test,
but it appears it fails with llilc due to EH.
> Exclusion of b99969

- include/Jit/EEMemoryManager.h
- lib/Jit/EEMemoryManager.cpp
Change r257294 (git hash cb4ab730d69) added alignment parameters to this
interface.  Update the signature of the override in LLILC's
EEMemoryManager, and update its body to take them into account when
computing the alignment to request from the CLR EE.
> Handle alignment in reserveAllocationSpace

- test/exclusion.targets
The test was recently updated (dotnet/coreclr@e251739) and now fails with
LLILC.  Opened llilc issue #1005 to fix.
> Exclude test CodeGenBringUpTests\RecursiveTailCall

- test/exclusion.targets
Change dotnet/coreclr@6b28be8 split VectorGet, VectorArrayInit, and
VectorCopyToArray into _r and _ro variants; update the exclusions
accordingly.
Also drop the apparently-stale references to VectorArrayGet.
> Update SIMD test exclusions

- lib/CoreDisTools/coredistools.cpp
- lib/ObjWriter/objwriter.cpp
Objectwriter and ObjectWriter and CoreDistools as tools loaded as DLLs.
They currently always register signal handlers for SIGABRT and SIGSEGV,
which interferes with CoreCLR's signal handlers. This caused unexpected
behavior and dumps in certain GCStress runs. So, this change removes
the use of LLVM's signal handlers.
> Don't register LLVM signal handlers in CoreCLR tools

- test/exclusion.targets
See dotnet/coreclr#2851. Closes #1000.
> Re-enable deltablue now that it no longer throws an exception

- lib/CoreDisTools/coredistools.cpp
The file moved in r258818 (llvm-mirror/llvm@b6242a88).  Update the
#include accordingly.
> Update MCDisassembler include path

- lib/ObjWriter/objwriter.cpp
This header moved from llvm/MC to llvm/MC/MCParser in r258917.
> Update MCTargetAsmParser.h include path

- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/CMakeLists.txt
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
This adds the following CFI unwind emission.
EmitCFIStart
EmitCFIEnd
EmitCFIBlob
The first two sets the range of the code that the frame covers.
The last one should be invoked for each offset of the code, if any.
The blob data format is shared by the one RyuJit layouts.
> Support for CFI Unwind

- lib/Jit/LLILCJit.cpp
Remove the code that sets `spp-no-statepoints` and
`rs4gc-use-deopt-bundles` to true; the options have been removed in
r259096 and r259129 and the behavior is now always as though they were set
to true.
> Remove references to deleted options

- lib/ObjWriter/objwriter.cpp
COFF::DEBUG_LINE_TABLES_HAVE_COLUMN_RECORDS no longer exists and has been
replaced by codeview::LineFlags::HaveColumns as of r259130; update
objwriter accordingly.
> Update for moved `HaveColumns` symbolic constant

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
Allow consumers of ObjWriter to define their own object file sections.
This commit adds support for simple data sections configured to be
writeable / read-only in each of the LLVM-supported output object file
formats.
> Custom Data Section Support for ObjWriter

- include/Jit/EEObjectLinkingLayer.h
- lib/Jit/LLILCJit.cpp
Something was flawed in my analysis of relocation handling in 10a9856, and
the double processing is causing ngen with llilc to generate incorrect
code.
Revert to our previous strategy of dragging along a copy of orc's
ObjectLinkingLayer with the relocation resolution suppressed, pending
working out an upstream refactoring to better handle this use case.
> Restore EEObjectLinkingLayer

- lib/GcInfo/GcInfo.cpp
LLVM change r256352 (llvm-mirror/llvm@da801219) had the effect of
switching the reporting at statepoints in LLILC from being annotated with
LocationKind::Direct (which would mean that the GC pointer being reported
is a pointer to the stack location indicated) to being annotated with
LocatoinKind::Indirect (which, correctly, means taht the stack location
being reported holds a GC pointer that the GC must track/update).  Update
LLILC's expectations when parsing the stack map accordingly.
> Expect `Indirect` pointers in stack map

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
This replaces the custom debug live emission code by CV line directives
that LLVM supports.
It also introduces Function/Module debug emission layers for the upcoming
work.
> Refactoring Line Number Emission for CV

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
This enables Dwarf line number emission for ObjectWriter.
Reused the code for Dwarf assembly debugging emission.
More fine grained logic like function/vars should be supported later.
With this, we can break into C# source using gdb/lldb on the binary
built from CoreRT in Linux/Osx.
> Support Dwarf LineNumber

- lib/CoreDisTools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.osx.10.10-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x64.Microsoft.NETCore.CoreDisTools.nuspec
The CoreDisTools package will be pushed to Microsoft.NetCore feed.
In order to match the convention in this feed, rename the CoreDistools
package from
toolchain.arch.Microsoft.DotNet.CoreDisTools.1.0.0-prerelease.nupkg
to
runtime.arch.Microsoft.NETcore.CoreDisTools.1.0.0-prerelease.nupkg
> Rename CoreDisTools Package

- test/exclusion.targets
When exception handling is enabled only 4 of the new tests
fail. However these also are exception handling tests, so
I've given all of the tests the exception handling issue number.
> Add exclusions for new failing tests.

- lib/CoreDisTools/coredistools.cpp
Address problem triggered on NetBSD-7.99.26 with GCC 4.8.2
```
make[1]: stopped in /tmp/pkgsrc-tmp/wip/llilc-git/work/build
/tmp/pkgsrc-tmp/wip/llilc-git/work/llilc/lib/CoreDisTools/coredistools.cpp:58:19:
error: declaration of 'TargetArch CorDisasm::TargetArch' [-fpermissive]
enum TargetArch TargetArch;
^
In file included from /tmp/pkgsrc-tmp/wip/llilc-git/work/llilc/lib/CoreDisTools/coredistools.cpp:35:0:
/tmp/pkgsrc-tmp/wip/llilc-git/work/llilc/include/CoreDisTools/coredistools.h:36:6:
error: changes meaning of 'TargetArch' from 'enum TargetArch' [-fpermissive]
enum TargetArch {
^
```
> Fix build on NetBSD: Solve name clash of TargetArch

- lib/Reader/reader.cpp
```
/tmp/pkgsrc-tmp/wip/llilc-git/work/llvm/tools/llilc/lib/Reader/reader.cpp:2282:26:
error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
if ((TargetOffset) < 0 || (TargetOffset) >= (BufSize))                     \
^
/tmp/pkgsrc-tmp/wip/llilc-git/work/llvm/tools/llilc/lib/Reader/reader.cpp:2413:7:
note: in expansion of macro 'CHECKTARGET'
CHECKTARGET(TargetOffset, ILInputSize);
^
/tmp/pkgsrc-tmp/wip/llilc-git/work/llvm/tools/llilc/lib/Reader/reader.cpp:2282:26:
error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
if ((TargetOffset) < 0 || (TargetOffset) >= (BufSize))                     \
^
/tmp/pkgsrc-tmp/wip/llilc-git/work/llvm/tools/llilc/lib/Reader/reader.cpp:2459:7:
note: in expansion of macro 'CHECKTARGET' …
```
> Fix build issue on NetBSD: Remove always false comparison

- lib/Jit/jitoptions.cpp
This patch addresses the following error on NetBSD-7.99.26 with GCC-4.8.5:
```
/tmp/pkgsrc-tmp/wip/llilc-git/work/llvm/tools/llilc/lib/Jit/jitoptions.cpp:
In constructor 'JitOptions::JitOptions(LLILCJitContext&)':
/tmp/pkgsrc-tmp/wip/llilc-git/work/llvm/tools/llilc/lib/Jit/jitoptions.cpp:66:36:
error: 'OptLevel' is not a class, namespace, or enumeration
EnableOptimization = OptLevel != OptLevel::DEBUG_CODE;
^
```
> Fix build issue on NetBSD: Correct namespace of OptLevel::DEBUG_CODE

- include/Jit/LLILCJit.h
- lib/Jit/LLILCJit.cpp
- lib/Jit/LLILCJit.exports
- lib/Jit/jitoptions.cpp
- lib/Reader/reader.cpp
Set up LLIC to use CorJitHost interface to access config values.
This change fixes LLILC build break.
> Use the CorJitHost interface.

- include/CoreDisTools/coredistools.h
- lib/CoreDisTools/coredistools.cpp
This change implements the near-diff functionality necessary for
asm-diff analysis. The near-differ compares two code-sections
for equivalency using the LLVM disassembler .
The two code blocks are disassembled in parallel looking for similar
instructions. In the case of constant operands, some heuristics are
applied via the areOffsetsEquivalent() callback to determine if the
constants can be considered equivalent (ex: constant offsets from the
start of the respective code sections).
> CoreDisTools: Implement Near-Differ

- netci.groovy
Our LLILC jobs should be generated by a groovy script like the rest of
the dotnet-ci jobs are. This change adds specifications for Windows
release and debug builds.
> Add netci.groovy for LLILC

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
Add a parameter to CreateCustomSection specifying a Comdat symbol to use
for the section being created. The selection policy is left as SelectAny
to allow the linker to pick.
> Support Comdat sections on Windows

- include/CoreDisTools/coredistools.h
- lib/CoreDisTools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.osx.10.10-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/coredistools.cpp
- lib/CoreDisTools/coredistools.exports
This commit has the following changes:
1) Separate out Asm-diff functionality from BlockInfo to a separate class
CorAsmDiff, which inherits from CorDisasm, to avoid passing around
some disassebler information.
2) Use customer provided printing routines via PrintControl interface
instead of printing ot stdout/stderr
3) Use Intel syntax for X86/X64 asm instead of the default GCC syntax
> CoreDisTools: Use Custom print API

- lib/CoreDisTools/coredistools.cpp
CoreDistools uses the customer provided print controls
for printing the log/error messages.
Unfortunately, SuperPMI appends a newline to all messages
passed into its print control. Therefore, CoreDisTools'
messages don't have the trailing newline.
This change adds the newline to the default printer, so that
other customers (ex: GCStress debugging) see the newline
when dumping a code block.
Also, adjusts the code block pretty printer's padding of
code bytes -- three characters are printed for each byte.
Swaroop.
> CoreDisTools: Add Newline to Default Printer

- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.osx.10.10-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x86.Microsoft.NETCore.CoreDisTools.nuspec
Add nuspec files to build X86 packages of the CoreDisTools library.
> CoreDisTOols: Build X86 packages

- Documentation/Getting-Started-For-Linux-and-OS-X.md
- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
Global data initialization is provided by special section types in the
MachO format whose contents are a list of function pointers to
initialize. Add ObjWriter support for these sections through the
existing CustomSectionAttributes enum.
> Add MachO S_MOD_INIT_FUNC_POINTERS section type support

- lib/CMakeLists.txt
To not track unnecessary build break, build objwriter/coredistools only.
> Build ObjWriter/CoreDisTools Only

- lib/CoreDisTools/coredistools.cpp
- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- Record sections that is used and endSection to ensure Section symbol creations.
- Register all executable sections to Dwarf sections so that debug info is created for them.
> Ending Section to Ensure Section Symbols

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
This change implements the EmitCFILsda function necessary for Unix exception
handling.
> Implement EmitCFILsda function in the objwriter

- lib/CoreDisTools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.osx.10.10-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.osx.10.10-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x86.Microsoft.NETCore.CoreDisTools.nuspec
Change the minor version to reflect changes in
https://github.com/dotnet/llilc/commit/cbb572ed5f404c822e9bdc1310f2842cb229acfa
There are no API changes in this version, small change to the implementation.
> Change Version of CoreDisTools library

- lib/CoreDisTools/.nuget/runtime.osx.10.10-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.osx.10.10-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.ubuntu.14.04-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win7-x86.Microsoft.NETCore.CoreDisTools.nuspec
Remove coredistools.h from the packages published for
CoreDistools library, since the header is checked into
the CoreCLR tree.
> Remove Coredistools header from Nuget Packages

- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.osx.10.11-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.osx.10.11-x86.Microsoft.NETCore.CoreDisTools.nuspec
Change the package version for OSX from 10.10 to 10.11
Fixes: https://github.com/dotnet/coreclr/issues/5602
> CoreDistools: Build packages for osx 10.11

- netci.groovy
Corlib is required for packaging and packaging is required for a clean build.
To get the jobs green we need to remove this.
> Remove skip of corlib build

- CMakeLists.txt
- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
llilc files were deleted from cmake.
ObjectWriter was updated to use the master branch of LLVM (when https://reviews.llvm.org/D29483 will be merged).
> Object writer was updated to use new LLVM

- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
Provide more precise control over custom sections. Previously we would
create a custom section for Comdat data and refer to it by name when
switching to it. However we really want custom sections with the same
name as existing sections, differing only on attributes or comdat name.
To accomplish this, remove the name -> MCSection mapping and provide an
extended API for switching sections that allows Comdat / attributes to
be specified.
> Extend SwitchSection API 

- lib/CMakeLists.txt
- lib/ObjWriter/CMakeLists.txt
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.h
export functions must only call ObjectWriter public methods.
Header file was creater.
Console options were deleted as unused.
Unclear code around TripleName was fixed.
It fixes warnings with OSX version.
> ObjectWriter refactoring

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
- lib/ObjWriter/objwriter.h
Fix problem with lldb debugging.
So after this fix we emit correct attributes for function symbols and sections.
The corresponding [CoreRT PR ](https://github.com/sandreenko/corert/commit/064cee1f14d7a5958e4e98285f57a41baf7338fa).
Some examples:
```
(lldb) breakpoint set --file Hello.cs --line 14
Breakpoint 1: where = Hello`Hello_Hello_Program__Main, address = 0x00000000005366a4
(lldb) r
Process 9580 launched: '/home/sergey/git/corert/tests/src/Simple/Hello/bin/Debug/x64/native/Hello' (x86_64)
Process 9580 stopped
* thread #1, name = 'Hello', stop reason = breakpoint 1.1
frame #0: 0x00000000005366a4 Hello`Hello_Hello_Program__Main at Hello.cs:14
11  	    internal class Program
12  	    {
13  	        private static void Main(string[] args)
-> 14  	        {
15  	            if …
```
> Debug function symbols for non windows

- lib/ObjWriter/typeBuilder.h
Type can be bigger than unsigned, Offset and SIze could be 64 bites long.
> Fix for some types

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.h
- lib/ObjWriter/typeBuilder.cpp
- lib/ObjWriter/typeBuilder.h
We need s_udt to guarantee that all UDT will be alive after the linker.
@nattress PTAL.
> emit S_UDT symbols to keep all UDT alive after the linker.

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
- lib/ObjWriter/objwriter.h
- lib/ObjWriter/typeBuilder.cpp
- lib/ObjWriter/typeBuilder.h
- Add support for pointers (LF_POINTER)
- Add support for MemberFunction records (LF_MFUNCTION)
- Add support for MemberFunctionId records (LF_MFUNC_ID)
- Remove auto attachment of a pointer record onto arrays/classes
- Add VTable shape handling
- Remove UniqueName info from PDBs as it isn't used by tools
> More complete debug data

- lib/CoreDisTools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.win-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win-x86.Microsoft.NETCore.CoreDisTools.nuspec
win7-x86 / win7-x64 are being deprecated and replaced with the generic win-x86 / win-x64 variants.
> Replace Windows NuGet Rids with generic variants
