dotnet/llilc

- lib/Reader/reader.cpp
* Remove a few unused variables
* Remove dead assignments
> Code cleanup

- include/Reader/reader.h
- include/Reader/readerenum.h
Documented reader.h's flow graph interface. Trimmed out some of the options that we'll never use, as well as a couple of useless helpers. Fix some typos.
> Some doxygen updates.

- Documentation/llilc-jit-eh.md
The LLVM plan is actually that filter invocations must be included in the
possible side-effects of calls that may throw exceptions.  That plan
should work for LLILC as well.
> Remove `beginfinally` intrinsic from EH plans

- Documentation/llilc-milestones.md
This adds a place for us to keep milestones that will take a PR.
These milestones will be linked to out of the wiki for reference. For
additions open a github issue to start a conversation then PR an edit
that has the new milestone.  When milestones are acheived strike through the txt.
> Add initial Bring up Milestones markdown.

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/readerir.cpp
I use llvm intrinsic to implement this.
I verified code sequence and ran it with a unit test,
which I will add to our test asset later.
> Support for interlockedCmpXchg

- lib/Reader/readerir.cpp
This arises in the case of types that are not present in metadata,
e.g. the type that contains unboxing stubs.
> Handle classes with no parent class.

- lib/Jit/LLILCJit.cpp
The current implementation of the GC statepoint design is incompatible
with fast ISel, which may visit a call to @llvm.experimental.gc_result
before the corresponding call to @llvm.experimental.gc_statepoint.
Unfortunately, disabling fast ISel turns out not to be as simple as
setting TargetOptions.EnableFastISel to false; instead, the command-line
option must be set to 'false'.
> Disable fast ISel.

- Documentation/llilc-jit-eh.md
- Update section on implicit null checks wrt the null check folding RFC.
- Mark reader catch support in EH branch implemented.  This was added in
e2bba9a
> Update EH document

- test/exclusion.targets
Just what it says on the tin. The corresponding CoreCLR PR is here: https://github.com/dotnet/coreclr/pull/1021
> Add exclusions for new JIT tests.

- README.md
Switch the badge and link for the Debug build to the badge and link for
the check build.
> Update the Debug build status badge.

- test/exclusion.targets
These all work now.
Closes #516, closes #480.
> Enable MDArray and CMOV tests.

- Documentation/llilc-jit-eh.md
The plan is to build on the model proposed in
http://thread.gmane.org/gmane.comp.compilers.llvm.devel/85783 - in
particular, EH edges will no longer target `landingpad`, but rather will
target `catchblock`/`cleanupblock` instructions that can guarantee
preserving the structure of dispatch code (which ultimately will be
perfomed by the runtime) during optimization.
> Update EH doc to reflect new WinEH proposal

- test/exclusion.targets
PR dotnet/coreclr#1120 added all remaining JIT\Regression test case. All under CLR-x86-JIT.
101 test cases have issue if run with LLILC. Exclude them. Issue https://github.com/dotnet/llilc/issues/628 is created for
investigation.
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28042\b28042
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b36471\b36471
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b48797\b48797
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b42929\b42929
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b73921\b73921
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41391\b41391
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b83690\b83690
JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b91917\b91917
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b37608\b37608
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b36274\b36274 …
> Exclude Regression\CLR-x86-JIT test cases that have issues with LLILC

- test/exclusion.targets
This depends on [CoreCLR PR #1130](https://github.com/dotnet/coreclr/pull/1130)
> Exclude failing IL tests.

- test/llilc_runtest.py
For users who have cloned CoreCLR into a directory named something other
than coreclr, the current checking of the current directory would fail.
This change allows the user to specify where their coreclr\tests
directory can be found, and allows users to run llilc_runtests.py
outside of coreclr\tests. The script will abort if runtest.cmd is not
found in the directory specified as the coreclr\tests path (or the
current working directory if none is specified). We then run runtest
specifying the full path.
> Add ability to specify CoreCLR tests directory

- lib/Jit/EEMemoryManager.cpp
Size passed to EEMemoryManager::registerEHFrames
includes the size of a padding UNWIND_CODE entry
so that the number of elements of the UnwindCode array is even.
Jit interface (allocUnwindInfo) expects the size reported to it not to include the padding
entry.
This was causing an assert in crossgen.exe when using llilcjit.
Closes #650.
> Fix unwind info reporting.

- Documentation/llilc-reader.md
Update implemented instructions, future work. Add a small section on ngen.
> Update reader document.

- lib/Jit/LLILCJit.cpp
The current call to getCommonSize fails because our function symbols are
not common symbols.
> Compute symbol sizes using common utility

- lib/Reader/readerir.cpp
1. Set "no-frame-pointer-elim on Pinvoke stubs.
> Changes for FI from master to MS

- lib/Reader/readerir.cpp
Also, fix getTypedAddress to allow pointers to TypedReferences.
Both of these NYIs showed up when ngen-ing mscorlib.dll.
Closes #361.
Closes #702.
> Implement unbox for nullable types.

- Documentation/Areas-To-Contribute.md
Documentation includes all issue links that were specified as ranges.
> Areas-To-Contribute issue ranges expanded.

- test/exclusion.targets
Include a test that is now passing.
Fix the issue reference for a few other bugs.
> Fix exlusion.targets

- lib/Jit/LLILCJit.cpp
- lib/Reader/readerir.cpp
This change add support to LLILC to send local variable information to
LLVM and then on to the CLR EE to be used in debugging. This change
adds:
* Support to the Reader to capture local variables as they are created.
We copy the logic from clang to specify if a local is a formal
parameter or a regular local variable, though the CLR does not seem to
care about this distinction. We assume that the local is in scope for
the full function.
* Update convertType to deal with struct types. Since we don't use the
type information for debugging, we can create a debug struct type with
no real information about the struct. This change is really just there
to prevent LLVM from attempting to reference a nullptr.
* Support to the ObjectLoadListener to extract DWARF information from
the ObjectFile for …
> Add debug support for locals

- test/llilc_hook.py
Added llilc_hook.py, a script used during desktop testing.
> Llilc_hook addition.

- include/Reader/readerir.h
Trivial change that fixes a few warnings.
> Fixes a few warnings in the reader that clang complains about

- test/exclusion.targets
Closes #420.
One test is invalid -- I've opened dotnet/coreclr#1440 to track removing such tests. One test passes. The rest require EH, so remapping to issue #13.
Closes #616.
These 3 tests all require EH, so remapping to issue #13.
Closes #547.
This test requires EH to pass, so remapping to issue #13.
> Reassess test cases with exclusion issues 420, 616 and 547.

- test/llilc_runtest.py
When specifying relative paths instead of absolute paths for arguments in llilc_runtest.py, the test failed.
The fix is to expand a full path for the given path.
Also added a check to verify it for the case of the required arguments.
> Fix for using relative path for llilc_runtest.py

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Static fields in GenIR caused thread-safety problem and were deleted.
Fixed bugs with box, ldind, store.
> Fix bugs with SIMD

- test/exclusion.targets
Closes #642.
These 8 tests now all pass, so I am removing the exclusions.
> Reclassify tests with exclusion issue 642.

- CMakeLists.txt
- lib/GcInfo/CMakeLists.txt
- lib/Jit/CMakeLists.txt
- lib/Reader/CMakeLists.txt
- lib/Reader/readerir.cpp
Fix a C4189 that I introduced recently. Turn on -WX for Windows builds for the code we author.
> Fix a warning and enable warnings as errors.

- lib/Reader/readerir.cpp
This will ensure that we know the incoming stack has an exception on it
when we first process the code in the handler.
> Add dummy predecessors for exception handlers

- lib/Reader/readerir.cpp
Closes #847.
When getting a value from a multidimensional array of reference types, the runtime creates an array get stub that does a bunch of raw pointer math feeding a `ldind.ref`. Ensure that we have reasonable typing for this case.
> Fix issues with ldind.ref and multidimensional array get

- lib/Jit/EEMemoryManager.cpp
The extra information passed in xdata is arranged differently now that
funclets aren't outlined into separate functions in LLVM IR.
> Update EH table parsing to new format

- lib/Jit/LLILCJit.cpp
The runtime_function field in the unwind_info in xdata gets created with a
relocation for the personality function.  The personality function we
specify is a synthetic declaration because this works well with the string
matching on the name that LLVM does and the EE doesn't actually use the
pointer in the xdata (it overwrites it with a pointer to the correct
routine before passing the xdata to the OS).  This change recognizes that
relocation and passes on processing it.
> Skip relocation for personality routine in xdata

- lib/Jit/LLILCJit.cpp
The object gets a function symbol for each funclet, so we need to sum
their sizes rather than trying to report each in turn.
> Update debug info emission to handle funclets

- Documentation/llilc-at-six-months.md
This writeup gives my perspective on the LLILC accomplishments made over the past six months and the challenges that remain.
> LLILC at Six Months: A Retrospective

- Documentation/llilc-at-six-months.md
> Fix some typos and update the gc struct section to reflect the new plan

- include/GcInfo/Target.h
- lib/Jit/LLILCJit.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Fix a few formatting issues that crept under the radar.
> Apply formatting

- lib/Reader/readerir.cpp
The logic to actually suppress handlers got dropped somewhere; re-enable
it by using calls instead of invokes everywhere when the flag is set.
Move the special logic for leaves inside of handlers under this flag (it
is correct only for the case that handlers are being suppressed).
> Fix SuppressExceptionHandlers processing

- include/Reader/readerir.h
- lib/Jit/LLILCJit.cpp
Some simple refactoring in anticipation of a further derived class that is specialized to read inlinees.
> Refactor GenIR's constructor

- lib/Reader/readerir.cpp
LLVM change r252372 (git commit 84cb8974b) removed the implicit
conversions between ilist/iplist iterators and pointers to the iterated
nodes (to force people to consider whether they might be trying to
illegally cast an end iterator to a node).  Update LLILC sources to match.
> Remove implicit list iterator conversions

- include/Reader/reader.h
- include/Reader/readerir.h
- lib/Reader/GenIRStubs.cpp
- lib/Reader/reader.cpp
- lib/Reader/readerir.cpp
Also remove as much of the related support code as I could find.
Also fix an unused local warning.
> Remove the eager tail recursion detection code

- lib/Reader/readerir.cpp
LLVM change r252694 (git commit 6426aea5) fixed a problem with getNextNode
when called on the last item in a list (instr in a block / block in a
functino), so that it now returns nullptr as expected, whereas previously
it cast the end iterator sentinel to a bogus node pointer.
This caused some tests to fail in createTemporary where we had evidently
(perhaps unwittingly) worked around the previous behavior by comparing the
result against the end iterator rather than nullptr.
This change updates createTemporary to deal directly in iterators when
setting the insertion point, rather than translating them back to
instructinos.  I audited all the other calls to getNextNode() in LLILC
sources, and changed several of them to likewise deal in iterators, to
simplify reasoning about the code.  There …
> Remove dubious usage of getNextNode

- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- utils/make_package.py
> Package spec for ObjectWriter on OSX

- test/exclusion.targets
All these require EH. All but one pass with ExecuteHandlers set.
Closes #967.
> Add excludes for new and refactored tests

- test/exclusion.targets
Exclude all new failing tests with generic failure reason. We can sort out why later.
> Blanket exclude of new failing tests

- test/exclusion.targets
@JosephTremoulet  Hopefully this is the last batch of these.
> Exclude varargs tests, fix typos

- test/exclusion.targets
Still using blanket reason #970, need triage.
> Exclude failing HFA tests

- test/exclusion.targets
Still tagged using generic issue #970, will sort it out later.
> Latest batch of excludes

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
Personality function and language-specific data area (LSDA) are now supplied.
> Unwind data emission of optional contents in ObjectWriter

- test/exclusion.targets
This is a new test that is failing with LLILC.  Issue #1000 opened to
track.
> Exclude V8\DeltaBlue

- lib/ObjWriter/objwriter.cpp
LLVM change r257712 (13d3e2ec) removed some members from COFF.h's
CodeViewIdentifiers enumeration that were used in the asm printer,
replacing them with equivalent constants from enums that it moved from
llvm-readobj to a shared header.  Update LLILC to use the shared enums.
> Update to shared enums

- test/exclusion.targets
Seeing some inconsisten test failures in the lab -- opened #1008 to track.
> Exclude failing tests

- utils/BuildPackages.ps1
This is part of https://github.com/dotnet/corert/issues/312.
> Add a script that builds ObjectWriter packages.

- test/exclusion.targets
> Exclude test inline\regression\mismatch32

- netci.groovy
The python script is case sensitive on the build type. Change debug and
release to all lower case. Add the Ubuntu jobs for debug and release
> Fix Windows Jobs and add Ubuntu jobs

- netci.groovy
> Revert "Fix Windows Jobs and add Ubuntu jobs"

- lib/CoreDisTools/coredistools.cpp
> Fix Build Break For OSX

- lib/CoreDisTools/coredistools.cpp
Remove VerifyPrefixDeocde() in the Core-Disassembler, because:
1) It doesn't serve any purpose -- CorDisasm::disasmInstruction()
uses machine opcodes (and not LLVM opcodes) to decide when to
continue disassembly past a prefix instruction
2) LLVM decodes different sets of prefixes as independent
instructions on X86 and AMD64 -- so this leads to unnecessary
overhead in maintaining the X86Prefix::IsLLVMInstruction state.
> CoreDisTools: Remove Prefix Decode Verification.

- lib/ObjWriter/objwriter.exports
I just realized we've missed exporting this.
> Add EmitCFILsda to ExportList

- README.md
Adds the code of conduct links to the project readme.
> Add MSOpen code of conduct statement

- lib/ObjWriter/objwriter.cpp
When a method is marked Comdat foldable (ie, generic methods, compiler
generated methods), ensure the related unwind info goes into a comdat
section associated with the same method. The linker will then atomically
take a method and its unwind info from the same object file. Previously
all unwind info was emitted into a single section and would cause
"Invalid .pdata contribution" errors at link time with comdat methods.
> Sharedunwindinfo

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
* Enable shared data between Elf object files by creating section groups for the shared comdat data to live in
> Linux Comdat section support

- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.exports
- lib/ObjWriter/objwriter.h
- lib/ObjWriter/typeBuilder.cpp
- lib/ObjWriter/typeBuilder.h
Array UDT.
Non-MD array has BaseClass, Count and ArrayElementType fields.
MD arrays also have each dimension length and lower bound values.
> Array type implementation

- lib/ObjWriter/.nuget/Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/runtime.json
- lib/ObjWriter/.nuget/toolchain.osx.10.10-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.ubuntu.14.04-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/.nuget/toolchain.win7-x64.Microsoft.DotNet.ObjectWriter.nuspec
- lib/ObjWriter/objwriter.cpp
- lib/ObjWriter/objwriter.h
- lib/ObjWriter/typeBuilder.cpp
- lib/ObjWriter/typeBuilder.h
+ version update.
PTAL @nattress, this PR is very small.
> Use references for args inside ObjectWriter 

- Documentation/Getting-Started-For-Windows.md
- Documentation/Setup-With-LLILC-Out-Of-LLVM-Tree.md
- Documentation/llilc-arch.md
Some spacing where incorrect, thus markdown was rendered the wrong way.
No product change is done.
> Fixed formatting in documentation

- Documentation/Getting-Started-For-Windows.md
- Documentation/Setup-With-LLILC-Out-Of-LLVM-Tree.md
- Documentation/llilc-arch.md
- lib/CoreDisTools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.json
- lib/CoreDisTools/.nuget/runtime.win-x64.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/.nuget/runtime.win-x86.Microsoft.NETCore.CoreDisTools.nuspec
- lib/CoreDisTools/coredistools.cpp
- lib/CoreDisTools/coredistools.exports
> Merge last changes in the master branch to ObjectWriter

- README.md
> update readme for ObjectWriter

- README.md
- lib/ObjWriter/objwriter.cpp
> Fix const qualifiers drop
